"""Curated dataset for the Health Systems map: notable hospital/health-system
OPERATORS (the businesses that own and run hospitals), sized small/mid/large/major
by hospital count. This is a hand-picked, sourced starting set — like seed_data.py,
not a bulk import. There is no hospital-count floor for inclusion; the tier cutoffs
below are a labeling scheme applied to whatever's picked, not a selection gate.

Originally built from big multi-state chains (via Becker's "largest health systems"
rankings), then extended state-by-state to cover single-state/regional flagship
systems too — the goal is real coverage across all 50 states, not just the ones
this tracker's RHTP funding data follows, though rural-relevant systems get
priority attention. A state with no entry here doesn't mean none exists — it means
no operator was both found and verifiable; skip a state rather than force a weak or
unsourced entry into it (see Alaska, Kansas, Montana, Wyoming, deliberately absent
as of the state-flagship pass below). Extend this the same way: add a row with a
real source_url.

Tiers are cut by hospital_count: major >=90, large 40-89, mid 15-39, small <15.
`confidence` follows the same convention as status_events/deadlines: 'confirmed'
when a source gave the figure directly for this org, 'approximate' when the
count is dated, mid-merger, or aggregated across a broader ranking page.
"""

HEALTH_SYSTEMS = [
    # --- major (90+ hospitals) ---
    {
        "name": "HCA Healthcare", "tier": "major", "ownership_type": "for-profit",
        "hq_city": "Nashville", "hq_state": "Tennessee", "hq_lat": 36.1627, "hq_lon": -86.7816,
        "hospital_count": 190, "notes": "Largest for-profit hospital operator in the US.",
        "source_url": "https://www.beckershospitalreview.com/rankings-and-ratings/100-of-the-largest-hospitals-and-health-systems-in-the-us-2026/",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "CommonSpirit Health", "tier": "major", "ownership_type": "nonprofit",
        "hq_city": "Chicago", "hq_state": "Illinois", "hq_lat": 41.8781, "hq_lon": -87.6298,
        "hospital_count": 158, "notes": "Nonprofit Catholic system formed by the 2019 merger of Catholic Health Initiatives and Dignity Health.",
        "source_url": "https://www.beckershospitalreview.com/rankings-and-ratings/100-of-the-largest-hospitals-and-health-systems-in-the-us-2026/",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "LifePoint Health", "tier": "major", "ownership_type": "for-profit",
        "hq_city": "Brentwood", "hq_state": "Tennessee", "hq_lat": 36.0331, "hq_lon": -86.7828,
        "hospital_count": 135, "notes": "For-profit; owns a majority of its hospitals through joint ventures with nonprofit partners.",
        "source_url": "https://www.beckershospitalreview.com/rankings-and-ratings/100-of-the-largest-hospitals-and-health-systems-in-the-us-2026/",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "Ascension", "tier": "major", "ownership_type": "nonprofit",
        "hq_city": "St. Louis", "hq_state": "Missouri", "hq_lat": 38.6270, "hq_lon": -90.1994,
        "hospital_count": 119, "notes": "One of the largest nonprofit Catholic health systems in the US. Its own find-care.ascension.org location search caps out broken nationwide/all-distance queries at ~14 results, so the hospital_roster entry for this operator (81 hospitals) was built with per-city, radius-limited searches across its actual 9-state footprint (FL, IL, IN, KS, MD, OK, TN, TX, WI) — Michigan, sometimes cited in older references, was fully divested. Coverage searched 1-3 major metros per state at up to 100mi, so some smaller or more rural facilities further out (especially in IL, IN, and TX) may be missing.",
        "source_url": "https://about.ascension.org/news/2026/03/ascension-named-fifth-largest-health-system-in-the-nation-reflecting-strategic-mission-aligned-growth",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "ScionHealth", "tier": "large", "ownership_type": "for-profit",
        "hq_city": "Louisville", "hq_state": "Kentucky", "hq_lat": 38.2527, "hq_lon": -85.7585,
        "hospital_count": 68, "notes": "Divested 8 community hospitals to LifePoint Health in a deal that closed March 2026; count reflects their own site's current total (62 specialty + 6 community hospitals).",
        "source_url": "https://www.scionhealth.com/find-a-location",
        "verified_at": "2026-09-17", "confidence": "confirmed",
    },
    {
        "name": "Trinity Health", "tier": "major", "ownership_type": "nonprofit",
        "hq_city": "Livonia", "hq_state": "Michigan", "hq_lat": 42.3684, "hq_lon": -83.3527,
        "hospital_count": 92, "notes": "Among the nation's three largest nonprofit Catholic health systems. Its corporate site's own location API is broken (returns zero results); the hospital_roster entry for this operator (58 hospitals) was built region-by-region from its ~10 separate regional-brand sites instead, so some states in its 23-state community footprint (e.g. AL, NC, MN, SD, CA, NJ) have no confirmed hospital and may be PACE/hospice/senior-living-only presence there.",
        "source_url": "https://www.beckershospitalreview.com/rankings-and-ratings/100-of-the-largest-hospitals-and-health-systems-in-the-us-2026/",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    # --- large (40-89 hospitals) ---
    {
        "name": "Advocate Health", "tier": "large", "ownership_type": "nonprofit",
        "hq_city": "Charlotte", "hq_state": "North Carolina", "hq_lat": 35.2271, "hq_lon": -80.8431,
        "hospital_count": 69, "notes": "Formed by the 2022 merger of Advocate Aurora Health and Atrium Health. Its Carolinas/Georgia/Alabama Atrium Health brand blocks automated access to its own location directory, so the hospital_roster entry for this operator (55 hospitals) is complete for Illinois and Wisconsin but likely missing some smaller Atrium-branded facilities.",
        "source_url": "https://en.wikipedia.org/wiki/Advocate_Health",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "Christus Health", "tier": "large", "ownership_type": "nonprofit",
        "hq_city": "Irving", "hq_state": "Texas", "hq_lat": 32.8140, "hq_lon": -96.9489,
        "hospital_count": 66, "notes": "Includes long-term care facilities and international hospitals (Mexico, Chile, Colombia); their own site's US-only hospital directory (TX/LA/NM) lists 32.",
        "source_url": "https://www.beckershospitalreview.com/rankings-and-ratings/100-of-the-largest-hospitals-and-health-systems-in-the-us-2026/",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "Community Health Systems", "tier": "large", "ownership_type": "for-profit",
        "hq_city": "Franklin", "hq_state": "Tennessee", "hq_lat": 35.9251, "hq_lon": -86.8689,
        "hospital_count": 65, "notes": None,
        "source_url": "https://www.beckershospitalreview.com/rankings-and-ratings/100-of-the-largest-hospitals-and-health-systems-in-the-us-2026/",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "Sanford Health", "tier": "large", "ownership_type": "nonprofit",
        "hq_city": "Sioux Falls", "hq_state": "South Dakota", "hq_lat": 43.5460, "hq_lon": -96.7313,
        "hospital_count": 45, "notes": "Largest rural-focused nonprofit health system in the US, including former Marshfield Clinic Health System (WI/MI) hospitals post-merger (Jan 2025); count is their own site's current hospital location listing, below the ~59 figure reported at merger time.",
        "source_url": "https://www.sanfordhealth.org/locations",
        "verified_at": "2026-09-17", "confidence": "confirmed",
    },
    {
        "name": "AdventHealth", "tier": "large", "ownership_type": "nonprofit",
        "hq_city": "Altamonte Springs", "hq_state": "Florida", "hq_lat": 28.6611, "hq_lon": -81.3656,
        "hospital_count": 57, "notes": "Seventh-day Adventist-affiliated nonprofit system.",
        "source_url": "https://en.wikipedia.org/wiki/AdventHealth",
        "verified_at": "2026-09-14", "confidence": "approximate",
    },
    {
        "name": "Baylor Scott & White Health", "tier": "large", "ownership_type": "nonprofit",
        "hq_city": "Dallas", "hq_state": "Texas", "hq_lat": 32.7767, "hq_lon": -96.7970,
        "hospital_count": 53, "notes": None,
        "source_url": "https://en.wikipedia.org/wiki/Baylor_Scott_%26_White_Health",
        "verified_at": "2026-09-14", "confidence": "approximate",
    },
    {
        "name": "Providence", "tier": "large", "ownership_type": "nonprofit",
        "hq_city": "Renton", "hq_state": "Washington", "hq_lat": 47.4829, "hq_lon": -122.2171,
        "hospital_count": 51, "notes": "Catholic-affiliated nonprofit system spanning the West Coast and Alaska/Montana/Texas.",
        "source_url": "https://www.beckershospitalreview.com/rankings-and-ratings/100-of-the-largest-hospitals-and-health-systems-in-the-us-2026/",
        "verified_at": "2026-09-14", "confidence": "approximate",
    },
    {
        "name": "Tenet Healthcare", "tier": "large", "ownership_type": "for-profit",
        "hq_city": "Dallas", "hq_state": "Texas", "hq_lat": 32.7767, "hq_lon": -96.7970,
        "hospital_count": 50, "notes": "Acute-care and specialty hospitals, as of Dec 31, 2025.",
        "source_url": "https://en.wikipedia.org/wiki/Tenet_Healthcare",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "Bon Secours Mercy Health", "tier": "large", "ownership_type": "nonprofit",
        "hq_city": "Cincinnati", "hq_state": "Ohio", "hq_lat": 39.1031, "hq_lon": -84.5120,
        "hospital_count": 47, "notes": "Catholic-affiliated nonprofit system.",
        "source_url": "https://www.beckershospitalreview.com/rankings-and-ratings/100-of-the-largest-hospitals-and-health-systems-in-the-us-2026/",
        "verified_at": "2026-09-14", "confidence": "approximate",
    },
    {
        "name": "UPMC", "tier": "large", "ownership_type": "nonprofit",
        "hq_city": "Pittsburgh", "hq_state": "Pennsylvania", "hq_lat": 40.4406, "hq_lon": -79.9959,
        "hospital_count": 40, "notes": "Academic-affiliated integrated system built around the University of Pittsburgh.",
        "source_url": "https://www.beckershospitalreview.com/rankings-and-ratings/100-of-the-largest-hospitals-and-health-systems-in-the-us-2026/",
        "verified_at": "2026-09-14", "confidence": "approximate",
    },
    {
        "name": "Kaiser Permanente", "tier": "large", "ownership_type": "nonprofit",
        "hq_city": "Oakland", "hq_state": "California", "hq_lat": 37.8044, "hq_lon": -122.2712,
        "hospital_count": 40, "notes": "Integrated payer-provider model, concentrated in a handful of states; relies on contracted/affiliate hospitals (not owned) in Colorado, Georgia, and the Mid-Atlantic. The hospital_roster entry for this operator (40 hospitals, region-by-region via its own location filters) matches this count almost exactly.",
        "source_url": "https://healthy.kaiserpermanente.org",
        "verified_at": "2026-09-17", "confidence": "confirmed",
    },
    # --- mid (15-39 hospitals) ---
    {
        "name": "Avera Health", "tier": "mid", "ownership_type": "nonprofit",
        "hq_city": "Sioux Falls", "hq_state": "South Dakota", "hq_lat": 43.5460, "hq_lon": -96.7313,
        "hospital_count": 38, "notes": "Faith-based regional system; most of its hospitals serve rural communities across SD, MN, IA, NE, ND.",
        "source_url": "https://en.wikipedia.org/wiki/Avera_Health",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "Intermountain Health", "tier": "mid", "ownership_type": "nonprofit",
        "hq_city": "Salt Lake City", "hq_state": "Utah", "hq_lat": 40.7608, "hq_lon": -111.8910,
        "hospital_count": 34, "notes": "The hospital_roster entry for this operator (29 hospitals, via its location-search API) found no owned hospitals in NV, KS, or WY despite dedicated searches, which may mean the 34-hospital figure counts a broader clinic/affiliate footprint rather than owned hospitals in all 7 states — treated as unconfirmed absence, not verified zero, for those 3 states.",
        "source_url": "https://www.beckershospitalreview.com/rankings-and-ratings/100-of-the-largest-hospitals-and-health-systems-in-the-us-2026/",
        "verified_at": "2026-09-17", "confidence": "approximate",
    },
    {
        "name": "Banner Health", "tier": "mid", "ownership_type": "nonprofit",
        "hq_city": "Phoenix", "hq_state": "Arizona", "hq_lat": 33.4484, "hq_lon": -112.0740,
        "hospital_count": 33, "notes": "Operates across 6 states.",
        "source_url": "https://en.wikipedia.org/wiki/Banner_Health",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "Universal Health Services", "tier": "mid", "ownership_type": "for-profit",
        "hq_city": "King of Prussia", "hq_state": "Pennsylvania", "hq_lat": 40.0893, "hq_lon": -75.3927,
        "hospital_count": 30, "notes": "Acute-care hospital count; also the largest US operator of behavioral-health facilities (380+ separately).",
        "source_url": "https://en.wikipedia.org/wiki/Universal_Health_Services",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "Cleveland Clinic", "tier": "mid", "ownership_type": "nonprofit",
        "hq_city": "Cleveland", "hq_state": "Ohio", "hq_lat": 41.4993, "hq_lon": -81.6944,
        "hospital_count": 23, "notes": "Academic medical system; count includes hospitals outside the US.",
        "source_url": "https://en.wikipedia.org/wiki/Cleveland_Clinic",
        "verified_at": "2026-09-14", "confidence": "approximate",
    },
    {
        "name": "Ballad Health", "tier": "mid", "ownership_type": "nonprofit",
        "hq_city": "Johnson City", "hq_state": "Tennessee", "hq_lat": 36.3134, "hq_lon": -82.3535,
        "hospital_count": 20, "notes": "Serves 29 mostly-rural Appalachian counties across TN, VA, NC and KY — formed via a state-approved COPA merger.",
        "source_url": "https://en.wikipedia.org/wiki/Ballad_Health",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "Novant Health", "tier": "mid", "ownership_type": "nonprofit",
        "hq_city": "Winston-Salem", "hq_state": "North Carolina", "hq_lat": 36.0999, "hq_lon": -80.2442,
        "hospital_count": 19, "notes": "Figure reported as of 2023; may undercount recent additions.",
        "source_url": "https://en.wikipedia.org/wiki/Novant_Health",
        "verified_at": "2026-09-14", "confidence": "approximate",
    },
    # --- small (<15 hospitals) ---
    {
        "name": "Essentia Health", "tier": "small", "ownership_type": "nonprofit",
        "hq_city": "Duluth", "hq_state": "Minnesota", "hq_lat": 46.7867, "hq_lon": -92.1005,
        "hospital_count": 14, "notes": "Serves rural and underserved communities across MN, WI and ND.",
        "source_url": "https://en.wikipedia.org/wiki/Essentia_Health",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    {
        "name": "Baptist Health (Kentucky)", "tier": "small", "ownership_type": "nonprofit",
        "hq_city": "Louisville", "hq_state": "Kentucky", "hq_lat": 38.2527, "hq_lon": -85.7585,
        "hospital_count": 10, "notes": "Founded 1924; not affiliated with the similarly-named Baptist Health systems in Florida or Arkansas.",
        "source_url": "https://en.wikipedia.org/wiki/Baptist_Health_(Kentucky_and_Southern_Indiana)",
        "verified_at": "2026-09-14", "confidence": "confirmed",
    },
    # --- state-flagship additions (single-state/regional, not just multi-state chains) ---
    {
        "name": 'MaineHealth', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Portland', "hq_state": 'Maine', "hq_lat": 43.6591, "hq_lon": -70.2568,
        "hospital_count": 9, "notes": "Maine's dominant health system and largest private employer. MaineHealth's own About page: \"a Level 1 trauma medical center, eight additional licensed hospitals\" (1 + 8 = 9).",
        "source_url": 'https://mainehealth.org/about-us',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Dartmouth Health', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Lebanon', "hq_state": 'New Hampshire', "hq_lat": 43.6424, "hq_lon": -72.2518,
        "hospital_count": 8, "notes": "NH/VT's dominant academic health system, anchored by Dartmouth-Hitchcock Medical Center. Count matches the 8 hospitals named on Dartmouth Health's own \"Our Members\" page (Dartmouth Hitchcock Medical Center, Alice Peck Day, Cheshire Medical Center, Mt. Ascutney, New London Hospital, Southwestern Vermont Medical Center, Valley Regional, Hampstead Hospital).",
        "source_url": 'https://www.dartmouth-health.org/',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'University of Vermont Health Network', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Burlington', "hq_state": 'Vermont', "hq_lat": 44.4759, "hq_lon": -73.2121,
        "hospital_count": 6, "notes": "Vermont's dominant health system, also serving northern New York; academic flagship affiliated with UVM's Larner College of Medicine.",
        "source_url": 'https://www.uvmhealth.org/about-the-uvm-health-network/the-uvm-health-network-hospitals',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Mass General Brigham', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Boston', "hq_state": 'Massachusetts', "hq_lat": 42.3467, "hq_lon": -71.0828,
        "hospital_count": 14, "notes": 'New England\'s largest health system, formed from the 1994 merger of Massachusetts General Hospital and Brigham and Women\'s Hospital (as "Partners HealthCare," renamed 2019).',
        "source_url": 'https://www.massgeneralbrigham.org/en/patient-care/services-and-specialties/find-a-location/our-hospitals',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Brown University Health', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Providence', "hq_state": 'Rhode Island', "hq_lat": 41.824, "hq_lon": -71.4128,
        "hospital_count": 7, "notes": "Rhode Island's largest hospital owner; formerly Lifespan, renamed in 2024. A full merger with Care New England (a distinct, smaller RI nonprofit) was blocked by regulators in 2022 and has not since closed.",
        "source_url": 'https://www.brownhealth.org/about',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Yale New Haven Health System', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'New Haven', "hq_state": 'Connecticut', "hq_lat": 41.3083, "hq_lon": -72.9279,
        "hospital_count": 5, "notes": "Connecticut's largest, most academically prominent health system, anchored by its Yale School of Medicine partnership. Hartford HealthCare (Hartford, CT; ~7 hospitals) is a comparably notable in-state alternate.",
        "source_url": 'https://en.wikipedia.org/wiki/Yale_New_Haven_Health_System',
        "verified_at": '2026-09-17', "confidence": 'approximate',
    },
    {
        "name": 'Northwell Health', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'New Hyde Park', "hq_state": 'New York', "hq_lat": 40.7412, "hq_lon": -73.6849,
        "hospital_count": 28, "notes": "New York State's largest healthcare provider and private employer; count reflects its May 2025 merger with Nuvance Health. NewYork-Presbyterian, Mount Sinai Health System, and Montefiore are also major, distinct NY systems.",
        "source_url": 'https://en.wikipedia.org/wiki/Northwell_Health',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'RWJBarnabas Health', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'West Orange', "hq_state": 'New Jersey', "hq_lat": 40.7987, "hq_lon": -74.2391,
        "hospital_count": 15, "notes": "New Jersey's largest academic health system (12 acute-care + 3 children's hospitals), formed by a 2016 merger; partnered with Rutgers University in 2018.",
        "source_url": 'https://www.rwjbh.org/why-rwjbarnabas-health-/facts-figures/',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Jefferson Health', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Philadelphia', "hq_state": 'Pennsylvania', "hq_lat": 39.9526, "hq_lon": -75.1652,
        "hospital_count": 32, "notes": 'Major Philadelphia-based system, distinct from UPMC (Pittsburgh) and Universal Health Services already in this dataset; grew substantially via its August 2024 merger with Lehigh Valley Health Network. Jefferson\'s own About page: "32 hospital campuses."',
        "source_url": 'https://www.jefferson.edu/about.html',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'ChristianaCare', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Wilmington', "hq_state": 'Delaware', "hq_lat": 39.7391, "hq_lon": -75.5398,
        "hospital_count": 3, "notes": "Delaware's largest health system and private employer; one of its three hospitals (Union Hospital) is just over the state line in Elkton, Maryland.",
        "source_url": 'https://en.wikipedia.org/wiki/ChristianaCare',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Johns Hopkins Medicine', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Baltimore', "hq_state": 'Maryland', "hq_lat": 39.2904, "hq_lon": -76.6122,
        "hospital_count": 6, "notes": 'World-renowned academic medical system anchored by Johns Hopkins Hospital/University. Johns Hopkins Medicine\'s own About page: "six academic and community hospitals." University of Maryland Medical System (also Baltimore) owns more hospitals (~11-13) but has less brand recognition.',
        "source_url": 'https://www.hopkinsmedicine.org/about/index.html',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Sentara Health', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Norfolk', "hq_state": 'Virginia', "hq_lat": 36.8508, "hq_lon": -76.2859,
        "hospital_count": 12, "notes": "Virginia's largest nonprofit health system, operating in VA and northeastern NC. A proposed 2020 merger with Cone Health was called off in 2021 and never completed.",
        "source_url": 'https://en.wikipedia.org/wiki/Sentara_Health',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'WVU Medicine', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Morgantown', "hq_state": 'West Virginia', "hq_lat": 39.6295, "hq_lon": -79.9559,
        "hospital_count": 25, "notes": "West Virginia's largest health system and largest private employer, spanning WV, OH, PA, and MD; a fast-moving, acquisition-heavy figure. WVU Medicine's own About Us page: \"25 hospitals across West Virginia, Ohio, Pennsylvania, and Maryland.\"",
        "source_url": 'https://wvumedicine.org/about-us/',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Duke Health', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Durham', "hq_state": 'North Carolina', "hq_lat": 35.994, "hq_lon": -78.8986,
        "hospital_count": 5, "notes": 'Elite academic medical system tied to Duke University. UNM Health-sized comparison aside, UNC Health (Chapel Hill, ~11 hospitals, state-owned) is a larger, also-distinct NC academic system worth knowing about.',
        "source_url": 'https://en.wikipedia.org/wiki/Duke_University_Health_System',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Prisma Health', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Greenville', "hq_state": 'South Carolina', "hq_lat": 34.8526, "hq_lon": -82.394,
        "hospital_count": 20, "notes": "South Carolina's largest nonprofit health system, formed in 2017 by the merger of Palmetto Health and Greenville Health System. Prisma's own FY2025 stats report: 14 acute-care campuses + 6 specialty hospitals (2 children's, 2 psychiatric, 1 rehab, 1 heart) = 20 total.",
        "source_url": 'https://prismahealth.org/pdfs/highlights-and-statistics-report-fy-2024',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Piedmont Healthcare', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Atlanta', "hq_state": 'Georgia', "hq_lat": 33.749, "hq_lon": -84.388,
        "hospital_count": 28, "notes": "Georgia's largest health system; has grown quickly via acquisition (older sources cite 16 or 26). Piedmont's own site: \"across 28 hospitals.\"",
        "source_url": 'https://www.piedmont.org/about-us/about-piedmont',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Orlando Health', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Orlando', "hq_state": 'Florida', "hq_lat": 28.5383, "hq_lon": -81.3792,
        "hospital_count": 25, "notes": "Florida's second-largest health system, distinct from AdventHealth (also Florida-HQ'd, already in this dataset); flagship houses Central Florida's only Level I trauma center.",
        "source_url": 'https://en.wikipedia.org/wiki/Orlando_Health',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'UAB Medicine', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Birmingham', "hq_state": 'Alabama', "hq_lat": 33.5186, "hq_lon": -86.8104,
        "hospital_count": 16, "notes": 'Public academic health system affiliated with the University of Alabama at Birmingham; flagship UAB Hospital is among the largest hospitals in the nation. Count matches a "16-hospital system" reference on uabmedicine.org, though it comes from an executive bio rather than a dedicated facts page.',
        "source_url": 'https://www.uabmedicine.org/about-uab-medicine/',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'North Mississippi Health Services', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Tupelo', "hq_state": 'Mississippi', "hq_lat": 34.2576, "hq_lon": -88.7034,
        "hospital_count": 8, "notes": 'The most notable system actually headquartered in Mississippi (as opposed to Memphis-based Baptist Memorial Health Care, which also operates MS hospitals); serves 24 counties across north MS and northwest AL.',
        "source_url": 'https://www.nmhs.net/about-us',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Baptist Memorial Health Care (Tennessee)', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Memphis', "hq_state": 'Tennessee', "hq_lat": 35.1495, "hq_lon": -90.049,
        "hospital_count": 25, "notes": 'Memphis-based; serves TN, MS, and AR. Unrelated to Baptist Health (Kentucky, already in this dataset), Baptist Health (Arkansas, added separately below), or the similarly-named Baptist systems in Florida and Alabama — disambiguated by name here deliberately. Count per Baptist Memorial\'s own March 2026 newsroom release announcing the Arkansas Methodist Medical Center merger, which "increas[ed] Baptist Memorial\'s hospitals to 25."',
        "source_url": 'https://www.baptistonline.org/about/newsroom',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'University Hospitals', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Cleveland', "hq_state": 'Ohio', "hq_lat": 41.4993, "hq_lon": -81.6944,
        "hospital_count": 21, "notes": 'Academic nonprofit system affiliated with Case Western Reserve, distinct from Cleveland Clinic and Bon Secours Mercy Health (both already in this dataset, also Ohio-based).',
        "source_url": 'https://www.uhhospitals.org/about-uh',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Corewell Health', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Grand Rapids', "hq_state": 'Michigan', "hq_lat": 42.9634, "hq_lon": -85.6681,
        "hospital_count": 21, "notes": "Formed by the 2022 merger of Beaumont Health (SE Michigan) and Spectrum Health (West Michigan); now the largest Michigan-based health system, distinct from Trinity Health (also Michigan-HQ'd, already in this dataset). Corewell's own site states \"21\" hospital facilities in a stats tile (Wikipedia's infobox says 22, but its own facility table only lists 21 by name).",
        "source_url": 'https://corewellhealth.org/about',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Indiana University Health', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Indianapolis', "hq_state": 'Indiana', "hq_lat": 39.7684, "hq_lon": -86.1581,
        "hospital_count": 16, "notes": "Indiana's largest and most comprehensive health system; academic affiliate of the IU School of Medicine. The only on-site statement of this figure is a stale October 2022 IU Health press release (\"IU Health's 16-hospital system\"); a July 2025 release describes 3 of its Indianapolis-area hospitals as consolidated into one \"IU Health Medical Center,\" suggesting the true current count may now be lower.",
        "source_url": 'https://en.wikipedia.org/wiki/Indiana_University_Health',
        "verified_at": '2026-09-17', "confidence": 'approximate',
    },
    {
        "name": 'Northwestern Medicine', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Chicago', "hq_state": 'Illinois', "hq_lat": 41.8781, "hq_lon": -87.6298,
        "hospital_count": 11, "notes": "Nationally-ranked academic system anchored by Northwestern Memorial Hospital, distinct from CommonSpirit Health (also Chicago-HQ'd, already in this dataset).",
        "source_url": 'https://www.nm.org/about-us',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'OSF HealthCare', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Peoria', "hq_state": 'Illinois', "hq_lat": 40.6936, "hq_lon": -89.589,
        "hospital_count": 16, "notes": 'Catholic nonprofit system spanning IL and MI (10 acute-care + 5 critical-access + 1 continuing-care hospital) — rural-relevant footprint distinct from Chicago-based Northwestern Medicine and CommonSpirit.',
        "source_url": 'https://www.osfhealthcare.org/about/facts/',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Froedtert ThedaCare Health', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Milwaukee', "hq_state": 'Wisconsin', "hq_lat": 43.0389, "hq_lon": -87.9065,
        "hospital_count": 18, "notes": 'Formed Jan. 2024 by the merger of Froedtert Health (Milwaukee) and ThedaCare (Appleton/Neenah); now the largest Wisconsin-based system. Marshfield Clinic Health System, once a WI candidate, merged into Sanford Health (already in this dataset) in Jan. 2025 and is no longer independent.',
        "source_url": 'https://en.wikipedia.org/wiki/ThedaCare%E2%80%93Froedtert_Health',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Mayo Clinic Health System', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Rochester', "hq_state": 'Minnesota', "hq_lat": 44.0121, "hq_lon": -92.4802,
        "hospital_count": 16, "notes": "Mayo Clinic's regional MN/IA/WI hospital network — a dated (2022) figure, separate from its flagship Rochester campus and its Arizona/Florida destination-medicine campuses; distinct from Essentia Health (also MN-HQ'd, already in this dataset). Spot-checked against Mayo Clinic Health System's own interactive locations page (2026-09-17): it doesn't publish a single stated total, but its \"Hospital and Clinic\"-tagged towns are consistent with a mid-teens count, corroborating rather than contradicting this figure.",
        "source_url": 'https://en.wikipedia.org/wiki/Mayo_Clinic_Health_System',
        "verified_at": '2026-09-17', "confidence": 'approximate',
    },
    {
        "name": 'UnityPoint Health', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'West Des Moines', "hq_state": 'Iowa', "hq_lat": 41.5772, "hq_lon": -93.7113,
        "hospital_count": 35, "notes": "Operates across IA, IL, and WI; distinct from MercyOne, which is already inside this dataset's Trinity Health roster. UnityPoint's own site: \"18 regional hospitals, 17 community network hospitals\" (18+17=35) — matches across both their About Us and locations pages; Wikipedia's higher \"39\" figure appears to be stale.",
        "source_url": 'https://www.unitypoint.org/about-unitypoint-health/our-organization/our-hospitals-and-locations',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Mercy (Missouri)', "tier": 'large', "ownership_type": 'nonprofit',
        "hq_city": 'Chesterfield', "hq_state": 'Missouri', "hq_lat": 38.6631, "hq_lon": -90.5771,
        "hospital_count": 55, "notes": 'Officially named just "Mercy" — labeled with its state here to distinguish it from Bon Secours Mercy Health (Ohio-HQ\'d) and Ascension (also St. Louis-based), both already in this dataset. Founded 1871; operates in MO, IL, AR, OK, and KS. Mercy\'s own quick-facts page cites "50 Hospitals" in a stat block but "55 acute care and specialty ... hospitals" in its boilerplate text; more recent (Dec 2025, May 2026) newsroom releases consistently use 55, so that figure is used here.',
        "source_url": 'https://www.mercy.net/newsroom/mercy-quick-facts/',
        "verified_at": '2026-09-17', "confidence": 'approximate',
    },
    {
        "name": 'Bryan Health', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Lincoln', "hq_state": 'Nebraska', "hq_lat": 40.8136, "hq_lon": -96.7026,
        "hospital_count": 6, "notes": "Nebraska's most notable independently-headquartered multi-hospital system, centered on Lincoln with expanded operations in Crete, Grand Island, Merrick County, and Kearney.",
        "source_url": 'https://en.wikipedia.org/wiki/Bryan_Health',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Norton Healthcare', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Louisville', "hq_state": 'Kentucky', "hq_lat": 38.2527, "hq_lon": -85.7585,
        "hospital_count": 9, "notes": "Louisville's dominant nonprofit system (6 in Louisville metro + 3 in southern Indiana); distinct from ScionHealth (for-profit, also Louisville-HQ'd) and Baptist Health (Kentucky), both already in this dataset.",
        "source_url": 'https://en.wikipedia.org/wiki/Norton_Healthcare',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'INTEGRIS Health', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Oklahoma City', "hq_state": 'Oklahoma', "hq_lat": 35.4676, "hq_lon": -97.5164,
        "hospital_count": 16, "notes": 'Oklahoma\'s largest nonprofit health system; other pages cite a larger "24 campuses" figure that includes specialty/community sites beyond hospitals. Their site has since rebranded from integrisok.com to integrishealth.org, which does not state a clean hospital total on its About, Locations, or News pages — still unconfirmed against their own site.',
        "source_url": 'https://en.wikipedia.org/wiki/INTEGRIS_Health',
        "verified_at": '2026-09-17', "confidence": 'approximate',
    },
    {
        "name": 'Baptist Health (Arkansas)', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Little Rock', "hq_state": 'Arkansas', "hq_lat": 34.7465, "hq_lon": -92.2896,
        "hospital_count": 11, "notes": 'Largest not-for-profit health system in Arkansas; unrelated to Baptist Health (Kentucky, already in this dataset), Baptist Memorial Health Care (Tennessee, added separately above), or Baptist systems in Florida — disambiguated by name here deliberately.',
        "source_url": 'https://www.baptist-health.com/about-baptist-health-arkansas/',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Ochsner Health', "tier": 'large', "ownership_type": 'nonprofit',
        "hq_city": 'New Orleans', "hq_state": 'Louisiana', "hq_lat": 29.9309, "hq_lon": -90.1093,
        "hospital_count": 47, "notes": "Louisiana's largest nonprofit system. Ochsner's own About page: \"expert care at its 47 hospitals\" — matches exactly, though it likely still blends wholly-owned hospitals with the broader Ochsner Health Network's managed/affiliated ones (a separate financial-disclosure document elsewhere cites a lower ~27 owned-only figure, but that number isn't published on ochsner.org itself).",
        "source_url": 'https://www.ochsner.org/about',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Trinity Health (Minot, ND)', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Minot', "hq_state": 'North Dakota', "hq_lat": 48.2325, "hq_lon": -101.2963,
        "hospital_count": 3, "notes": 'A small, entirely separate organization from Trinity Health (Livonia, Michigan, already in this dataset) that happens to share the same name — Wikipedia itself flags the collision. Runs 3 hospitals in and around Minot, ND.',
        "source_url": 'https://en.wikipedia.org/wiki/Trinity_Health_(Minot,_North_Dakota)',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Monument Health', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Rapid City', "hq_state": 'South Dakota', "hq_lat": 44.0805, "hq_lon": -103.231,
        "hospital_count": 5, "notes": 'Formerly Rapid City Regional Hospital system; dominant system in the Black Hills region, distinct from Avera Health and Sanford Health (both already in this dataset, also SD-based).',
        "source_url": 'https://monument.health/about-us/',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'UCHealth', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Aurora', "hq_state": 'Colorado', "hq_lat": 39.7294, "hq_lon": -104.8319,
        "hospital_count": 15, "notes": 'Operates acute-care hospitals across CO, WY, and western NE. Centura Health, a former CO candidate, was fully dissolved and split between CommonSpirit and AdventHealth by 2024 and no longer exists as an independent operator.',
        "source_url": 'https://en.wikipedia.org/wiki/UCHealth',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Presbyterian Healthcare Services', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Albuquerque', "hq_state": 'New Mexico', "hq_lat": 35.0844, "hq_lon": -106.6504,
        "hospital_count": 9, "notes": "New Mexico's largest locally-owned, not-for-profit integrated health system, combining hospitals with its own health plan.",
        "source_url": 'https://www.phs.org/locations/hospitals',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'HonorHealth', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Scottsdale', "hq_state": 'Arizona', "hq_lat": 33.4942, "hq_lon": -111.9261,
        "hospital_count": 9, "notes": "Formed by a 2013 merger; Phoenix-area system distinct from Banner Health (also Arizona-HQ'd, already in this dataset). HonorHealth's own site: \"nine acute-care hospitals.\"",
        "source_url": 'https://www.honorhealth.com/company',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'University of Utah Health', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Salt Lake City', "hq_state": 'Utah', "hq_lat": 40.7608, "hq_lon": -111.891,
        "hospital_count": 5, "notes": "The Mountain West's only academic health system, part of the University of Utah; distinct in mission and governance from Intermountain Health (already in this dataset, also Utah-HQ'd). Their own About page: \"Five hospitals and 12 community health care centers.\"",
        "source_url": 'https://healthcare.utah.edu/about',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Renown Health', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Reno', "hq_state": 'Nevada', "hq_lat": 39.5296, "hq_lon": -119.8138,
        "hospital_count": 4, "notes": 'The only large locally-owned nonprofit health system in Northern Nevada. Their own About page describes "two acute care hospitals, a children\'s hospital, [and] a rehabilitation hospital" (4 total) — a 2026 newsroom item notes plans to build a standalone children\'s hospital, currently housed within Renown Regional.',
        "source_url": 'https://www.renown.org/About',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": "St. Luke's Health System", "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Boise', "hq_state": 'Idaho', "hq_lat": 43.615, "hq_lon": -116.2023,
        "hospital_count": 8, "notes": "Idaho's only locally-governed, physician-led nonprofit health system and the state's largest employer; distinct from Saint Alphonsus (already inside this dataset's Trinity Health roster). Matches the 8 facilities named on St. Luke's own \"Hospitals and Medical Centers\" page (Boise, Jerome, McCall, Meridian, Mountain Home, Nampa, Twin Falls, Wood River) — some other sources cite 6.",
        "source_url": 'https://www.stlukesonline.org/find-a-location',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'MultiCare Health System', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Tacoma', "hq_state": 'Washington', "hq_lat": 47.2529, "hq_lon": -122.4443,
        "hospital_count": 11, "notes": 'Tacoma-founded (1882) system that has grown via recent mergers (Yakima Memorial 2023, Overlake Medical Center 2024); distinct from Providence (already in this dataset, also WA-based).',
        "source_url": 'https://en.wikipedia.org/wiki/MultiCare_Health_System',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Legacy Health', "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Portland', "hq_state": 'Oregon', "hq_lat": 45.5152, "hq_lon": -122.6784,
        "hospital_count": 7, "notes": "Oregon's largest Oregon-based nonprofit health system; a planned full integration with Oregon Health & Science University was announced in 2024 and called off in May 2025.",
        "source_url": 'https://en.wikipedia.org/wiki/Legacy_Health',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": 'Sutter Health', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Sacramento', "hq_state": 'California', "hq_lat": 38.5816, "hq_lon": -121.4944,
        "hospital_count": 27, "notes": 'Large nonprofit system in Northern/Central California, distinct from Kaiser Permanente (already in this dataset, also CA-based); long a subject of state antitrust scrutiny over pricing. Sutter\'s own site is internally inconsistent — its overview page says "more than 20" and separately "21," while its dedicated "About Our Hospitals" page says "Our 27 hospitals"; 27 is used here as the most specific, dedicated statement, but treat this as a real open discrepancy, not a typo.',
        "source_url": 'https://www.sutterhealth.org/about/our-hospitals',
        "verified_at": '2026-09-17', "confidence": 'approximate',
    },
    {
        "name": 'Adventist Health', "tier": 'mid', "ownership_type": 'nonprofit',
        "hq_city": 'Roseville', "hq_state": 'California', "hq_lat": 38.7521, "hq_lon": -121.288,
        "hospital_count": 27, "notes": "Serves the West Coast and Hawaii. Despite the very similar name, this is a completely separate company from AdventHealth (Florida-HQ'd, already in this dataset) — both trace to the Seventh-day Adventist Church but are independently governed.",
        "source_url": 'https://en.wikipedia.org/wiki/Adventist_Health',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": "The Queen's Health Systems", "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Honolulu', "hq_state": 'Hawaii', "hq_lat": 21.3069, "hq_lon": -157.8583,
        "hospital_count": 6, "notes": "Hawaii's oldest hospital system, tracing to 1859; larger by hospital count than the also-notable Hawaii Pacific Health (Honolulu, 4 hospitals).",
        "source_url": 'https://www.queens.org/about/',
        "verified_at": '2026-09-17', "confidence": 'confirmed',
    },
    {
        "name": "University of Kansas Health System", "tier": 'small', "ownership_type": 'nonprofit',
        "hq_city": 'Kansas City', "hq_state": 'Kansas', "hq_lat": 39.1142, "hq_lon": -94.6275,
        "hospital_count": 7, "notes": "Nonprofit academic medical center, independent of state funding since 1998. No single official page states a total hospital count — this figure is counted directly off their own locations page (The University of Kansas Hospital main campus, St. Francis Campus in Topeka, Olathe Hospital, Paola Hospital, Great Bend Campus Hospital, Liberty Hospital in MO, and Marillac Campus, a behavioral-health hospital in Overland Park); distinct from Ascension Via Christi (already inside this dataset's Ascension roster).",
        "source_url": 'https://www.kansashealthsystem.com/locations',
        "verified_at": '2026-09-17', "confidence": 'approximate',
    },
]
