"""Curated roster of hospitals by parent health-system operator, used to tag
individual HIFLD live-map facilities with "part of <Operator>" where a match is
found. A snapshot, not live data — see the "How this data stays current" note in
README.md. Matching is done client-side (static/app.js) against the live HIFLD
facility feed by normalized name + city + state; a HIFLD hospital with no match
here is shown as "Parent operator not identified," never guessed.

Extend this the same way as health_systems_data.py: one HOSPITAL_ROSTERS entry
per company, each hospital row sourced from that company's own official location
directory (cited in source_url), with a verified_at date.
"""

HOSPITAL_ROSTERS = [
    {
        "company": "HCA Healthcare",
        "source_url": "https://www.hcahealthcare.com/locations/",
        "verified_at": "2026-09-17",
        "hospitals": [
            {"name": "LEE'S SUMMIT MEDICAL CENTER", "city": 'Lees Summit', "state": 'MO'},
            {"name": 'RESEARCH MEDICAL CENTER', "city": 'Kansas City', "state": 'MO'},
            {"name": 'LAFAYETTE REGIONAL HEALTH CENTER', "city": 'Lexington', "state": 'MO'},
            {"name": 'BELTON REGIONAL MEDICAL CENTER', "city": 'Belton', "state": 'MO'},
            {"name": 'CENTERPOINT MEDICAL CENTER', "city": 'Independence', "state": 'MO'},
            {"name": 'BLUE RIDGE REGIONAL HOSPITAL', "city": 'Spruce Pine', "state": 'NC'},
            {"name": 'TRANSYLVANIA REGIONAL HOSPITAL', "city": 'Brevard', "state": 'NC'},
            {"name": 'ANGEL MEDICAL CENTER', "city": 'Franklin', "state": 'NC'},
            {"name": 'MCDOWELL HOSPITAL', "city": 'Marion', "state": 'NC'},
            {"name": 'HIGHLANDS-CASHIERS HOSPITAL', "city": 'Highlands', "state": 'NC'},
            {"name": 'MISSION HOSPITAL', "city": 'Asheville', "state": 'NC'},
            {"name": 'CAREPARTNERS REHABILITATION HOSPITAL', "city": 'Asheville', "state": 'NC'},
            {"name": 'HCA FLORIDA ST. LUCIE HOSPITAL', "city": 'Port St Lucie', "state": 'FL'},
            {"name": 'HCA FLORIDA AVENTURA HOSPITAL', "city": 'Aventura', "state": 'FL'},
            {"name": 'HCA FLORIDA WOODMONT HOSPITAL', "city": 'Tamarac', "state": 'FL'},
            {"name": 'HCA FLORIDA TWIN CITIES HOSPITAL', "city": 'Niceville', "state": 'FL'},
            {"name": 'HCA FLORIDA LAWNWOOD HOSPITAL', "city": 'Fort Pierce', "state": 'FL'},
            {"name": 'HCA FLORIDA LAKE MONROE HOSPITAL', "city": 'Sanford', "state": 'FL'},
            {"name": 'HCA FLORIDA WEST HOSPITAL', "city": 'Pensacola', "state": 'FL'},
            {"name": 'HCA FLORIDA OAK HILL HOSPITAL', "city": 'Brooksville', "state": 'FL'},
            {"name": 'HCA FLORIDA BRANDON HOSPITAL', "city": 'Brandon', "state": 'FL'},
            {"name": 'UCF LAKE NONA HOSPITAL', "city": 'Orlando', "state": 'FL'},
            {"name": 'HCA FLORIDA CAPITAL HOSPITAL', "city": 'Tallahassee', "state": 'FL'},
            {"name": 'HCA FLORIDA JFK NORTH HOSPITAL', "city": 'West Palm Beach', "state": 'FL'},
            {"name": 'HCA FLORIDA PALMS WEST HOSPITAL', "city": 'Loxahatchee', "state": 'FL'},
            {"name": 'HCA FLORIDA LAKE CITY HOSPITAL', "city": 'Lake City', "state": 'FL'},
            {"name": 'HCA FLORIDA NORTH FLORIDA HOSPITAL', "city": 'Gainesville', "state": 'FL'},
            {"name": 'HCA FLORIDA RAULERSON HOSPITAL', "city": 'Okeechobee', "state": 'FL'},
            {"name": 'HCA FLORIDA MEMORIAL HOSPITAL', "city": 'Jacksonville', "state": 'FL'},
            {"name": 'HCA FLORIDA GULF COAST HOSPITAL', "city": 'Panama City', "state": 'FL'},
            {"name": 'HCA FLORIDA JFK HOSPITAL', "city": 'Atlantis', "state": 'FL'},
            {"name": 'HCA FLORIDA KENDALL HOSPITAL', "city": 'Miami', "state": 'FL'},
            {"name": 'HCA FLORIDA MERCY HOSPITAL', "city": 'Miami', "state": 'FL'},
            {"name": 'HCA FLORIDA TRINITY HOSPITAL', "city": 'Trinity', "state": 'FL'},
            {"name": 'HCA FLORIDA NORTHWEST HOSPITAL', "city": 'Margate', "state": 'FL'},
            {"name": 'HCA FLORIDA ENGLEWOOD HOSPITAL', "city": 'Englewood', "state": 'FL'},
            {"name": 'HCA FLORIDA ORANGE PARK HOSPITAL', "city": 'Orange Park', "state": 'FL'},
            {"name": 'HCA FLORIDA - OCALA HOSPITAL', "city": 'Ocala', "state": 'FL'},
            {"name": 'HCA FLORIDA WEST MARION HOSPITAL', "city": 'Ocala', "state": 'FL'},
            {"name": 'OVIEDO MEDICAL CENTER', "city": 'Oviedo', "state": 'FL'},
            {"name": 'HCA FLORIDA LEHIGH HOSPITAL', "city": 'Lehigh Acres', "state": 'FL'},
            {"name": 'HCA FLORIDA WESTSIDE HOSPITAL', "city": 'Plantation', "state": 'FL'},
            {"name": 'HCA FLORIDA SARASOTA DOCTORS HOSPITAL', "city": 'Sarasota', "state": 'FL'},
            {"name": 'HCA FLORIDA FORT WALTON-DESTIN HOSPITAL', "city": 'Fort Walton Beach', "state": 'FL'},
            {"name": 'HCA FLORIDA WEST TAMPA HOSPITAL', "city": 'Tampa', "state": 'FL'},
            {"name": 'HCA FLORIDA SOUTH TAMPA HOSPITAL', "city": 'Tampa', "state": 'FL'},
            {"name": 'HCA FLORIDA OSCEOLA HOSPITAL', "city": 'Kissimmee', "state": 'FL'},
            {"name": 'HCA FLORIDA POINCIANA HOSPITAL', "city": 'Kissimmee', "state": 'FL'},
            {"name": 'HCA FLORIDA BAYONET POINT HOSPITAL', "city": 'Hudson', "state": 'FL'},
            {"name": 'HCA FLORIDA UNIVERSITY HOSPITAL', "city": 'Davie', "state": 'FL'},
            {"name": 'HCA FLORIDA NORTHSIDE HOSPITAL', "city": 'St Petersburg', "state": 'FL'},
            {"name": 'HCA FLORIDA ST. PETERSBURG HOSPITAL', "city": 'St Petersburg', "state": 'FL'},
            {"name": 'HCA FLORIDA SOUTH SHORE HOSPITAL', "city": 'Sun City Center', "state": 'FL'},
            {"name": 'HCA FLORIDA LARGO WEST HOSPITAL', "city": 'Largo', "state": 'FL'},
            {"name": 'HCA FLORIDA LARGO HOSPITAL', "city": 'Largo', "state": 'FL'},
            {"name": 'HCA FLORIDA CITRUS HOSPITAL', "city": 'Inverness', "state": 'FL'},
            {"name": 'HCA FLORIDA PUTNAM HOSPITAL', "city": 'Palatka', "state": 'FL'},
            {"name": 'HCA FLORIDA HIGHLANDS HOSPITAL', "city": 'Sebring', "state": 'FL'},
            {"name": 'HCA FLORIDA FAWCETT HOSPITAL', "city": 'Port Charlotte', "state": 'FL'},
            {"name": 'HCA FLORIDA BLAKE HOSPITAL', "city": 'Bradenton', "state": 'FL'},
            {"name": 'ALASKA REGIONAL HOSPITAL', "city": 'Anchorage', "state": 'AK'},
            {"name": 'RAPIDES REGIONAL MEDICAL CENTER', "city": 'Alexandria', "state": 'LA'},
            {"name": 'EASTERN IDAHO RMC', "city": 'Idaho Falls', "state": 'ID'},
            {"name": 'WEST VALLEY MEDICAL CENTER', "city": 'Caldwell', "state": 'ID'},
            {"name": 'FRISBIE MEMORIAL HOSPITAL', "city": 'Rochester', "state": 'NH'},
            {"name": 'PORTSMOUTH REGIONAL HOSPITAL', "city": 'Portsmouth', "state": 'NH'},
            {"name": 'PARKLAND MEDICAL CENTER', "city": 'Derry', "state": 'NH'},
            {"name": 'CATHOLIC MEDICAL CENTER', "city": 'Manchester', "state": 'NH'},
            {"name": 'LEWISGALE HOSPITAL-MONTGOMERY', "city": 'Blacksburg', "state": 'VA'},
            {"name": 'SPOTSYLVANIA REGIONAL MEDICAL CENTER', "city": 'Fredericksburg', "state": 'VA'},
            {"name": 'JOHNSTON-WILLIS HOSPITAL', "city": 'Richmond', "state": 'VA'},
            {"name": 'CHIPPENHAM HOSPITAL', "city": 'Richmond', "state": 'VA'},
            {"name": 'RETREAT DOCTORS HOSPITAL', "city": 'Richmond', "state": 'VA'},
            {"name": 'HENRICO DOCTORS HOSPITAL - FOREST', "city": 'Richmond', "state": 'VA'},
            {"name": 'PARHAM DOCTORS HOSPITAL', "city": 'Richmond', "state": 'VA'},
            {"name": 'LEWISGALE MEDICAL CENTER', "city": 'Salem', "state": 'VA'},
            {"name": 'STONESPRINGS HOSPITAL CENTER', "city": 'Sterling', "state": 'VA'},
            {"name": 'RESTON HOSPITAL CENTER', "city": 'Reston', "state": 'VA'},
            {"name": 'TRICITIES HOSPITAL', "city": 'Hopewell', "state": 'VA'},
            {"name": 'LEWISGALE HOSPITAL-ALLEGHANY', "city": 'Low Moor', "state": 'VA'},
            {"name": 'LEWISGALE HOSPITAL-PULASKI', "city": 'Pulaski', "state": 'VA'},
            {"name": 'ROUND ROCK MEDICAL CENTER', "city": 'Round Rock', "state": 'TX'},
            {"name": 'MEDICAL CITY LAS COLINAS', "city": 'Irving', "state": 'TX'},
            {"name": 'HCA HOUSTON PEARLAND', "city": 'Pearland', "state": 'TX'},
            {"name": 'MEDICAL CITY NORTH HILLS', "city": 'North Richland Hills', "state": 'TX'},
            {"name": 'VALLEY REGIONAL MEDICAL CENTER', "city": 'Brownsville', "state": 'TX'},
            {"name": 'METHODIST HOSPITAL ATASCOSA', "city": 'Jourdanton', "state": 'TX'},
            {"name": 'MEDICAL CITY PLANO', "city": 'Plano', "state": 'TX'},
            {"name": 'HEART HOSPITAL OF AUSTIN', "city": 'Austin', "state": 'TX'},
            {"name": 'SOUTH AUSTIN MEDICAL CENTER', "city": 'Austin', "state": 'TX'},
            {"name": 'NORTH AUSTIN MEDICAL CENTER', "city": 'Austin', "state": 'TX'},
            {"name": "ST DAVID'S MEDICAL CENTER", "city": 'Austin', "state": 'TX'},
            {"name": "ST. DAVID'S SURGICAL HOSPITAL", "city": 'Austin', "state": 'TX'},
            {"name": 'HCA HOUSTON MAINLAND', "city": 'Texas City', "state": 'TX'},
            {"name": 'MEDICAL CITY LEWISVILLE', "city": 'Lewisville', "state": 'TX'},
            {"name": 'MEDICAL CITY SACHSE', "city": 'Sachse', "state": 'TX'},
            {"name": 'RIO GRANDE REGIONAL HOSPITAL', "city": 'McAllen', "state": 'TX'},
            {"name": 'METHODIST HOSPITAL HILL COUNTRY', "city": 'Fredericksburg', "state": 'TX'},
            {"name": 'METHODIST HOSPITAL', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METHODIST HOSPITAL LANDMARK', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METHODIST TEXSAN HOSPITAL', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METHODIST SPECIALTY & TRANSPLANT HOSP', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METHODIST REHABILITATION HOSPITAL TEXSAN', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METHODIST HOSPITAL WESTOVER HILLS', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METHODIST HOSPITAL STONE OAK', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METROPOLITAN METHODIST HOSPITAL', "city": 'San Antonio', "state": 'TX'},
            {"name": 'MEDICAL CITY WEATHERFORD', "city": 'Weatherford', "state": 'TX'},
            {"name": 'MEDICAL CITY MH FRISCO', "city": 'Frisco', "state": 'TX'},
            {"name": 'MEDICAL CITY FRISCO', "city": 'Frisco', "state": 'TX'},
            {"name": 'HCA HOUSTON SOUTHEAST', "city": 'Pasadena', "state": 'TX'},
            {"name": 'LAS PALMAS MEDICAL CENTER', "city": 'El Paso', "state": 'TX'},
            {"name": 'DEL SOL MEDICAL CENTER', "city": 'El Paso', "state": 'TX'},
            {"name": 'MEDICAL CITY GREEN OAKS HOSPITAL DALLAS', "city": 'Dallas', "state": 'TX'},
            {"name": 'MEDICAL CITY HEART & SPINE', "city": 'Dallas', "state": 'TX'},
            {"name": 'MEDICAL CITY DALLAS', "city": 'Dallas', "state": 'TX'},
            {"name": 'HCA HOUSTON TOMBALL', "city": 'Tomball', "state": 'TX'},
            {"name": 'MEDICAL CITY DECATUR', "city": 'Decatur', "state": 'TX'},
            {"name": 'NORTHEAST METHODIST HOSPITAL', "city": 'Live Oak', "state": 'TX'},
            {"name": 'HCA HOUSTON N CYPRESS', "city": 'Cypress', "state": 'TX'},
            {"name": 'MEDICAL CITY DENTON', "city": 'Denton', "state": 'TX'},
            {"name": 'MEDICAL CITY MCKINNEY', "city": 'McKinney', "state": 'TX'},
            {"name": 'HCA HOUSTON KINGWOOD', "city": 'Kingwood', "state": 'TX'},
            {"name": "ST. DAVID'S GEORGETOWN", "city": 'Georgetown', "state": 'TX'},
            {"name": 'CORPUS CHRISTI MEDICAL CENTER', "city": 'Corpus Christi', "state": 'TX'},
            {"name": 'LOC AT UCLH - GBP', "city": 'London', "state": 'EN'},
            {"name": 'HARLEY STREET CLINIC', "city": 'London', "state": 'EN'},
            {"name": 'THE HARBORNE HOSPITAL', "city": 'Birmingham', "state": 'EN'},
            {"name": 'THE PORTLAND HOSPITAL', "city": 'London', "state": 'EN'},
            {"name": 'GRAND STRAND MEDICAL CENTER', "city": 'Myrtle Beach', "state": 'SC'},
            {"name": 'HCA HEALTHCARE COLLETON HOSPITAL', "city": 'Walterboro', "state": 'SC'},
            {"name": 'HCA HEALTHCARE TRIDENT HOSPITAL', "city": 'Charleston', "state": 'SC'},
            {"name": 'GOOD SAMARITAN HOSPITAL', "city": 'Los Gatos', "state": 'CA'},
            {"name": 'GOOD SAMARITAN HOSPITAL', "city": 'San Jose', "state": 'CA'},
            {"name": 'LOS ROBLES HOSPITAL AND MEDICAL CENTER', "city": 'Thousand Oaks', "state": 'CA'},
            {"name": 'LOS ROBLES HOSPITAL AND MEDICAL CENTER', "city": 'West Lake Village', "state": 'CA'},
            {"name": 'RIVERSIDE COMMUNITY HOSPITAL', "city": 'Riverside', "state": 'CA'},
            {"name": 'MOUNTAINVIEW HOSPITAL', "city": 'Las Vegas', "state": 'NV'},
            {"name": 'SOUTHERN HILLS HOSP & MED CTR-LAS VEGAS', "city": 'Las Vegas', "state": 'NV'},
            {"name": 'SUNRISE HOSPITAL AND MEDICAL CENTER', "city": 'Las Vegas', "state": 'NV'},
            {"name": 'HCA HEALTHONE SWEDISH', "city": 'Englewood', "state": 'CO'},
            {"name": 'HCA HEALTHONE SKY RIDGE', "city": 'Lone Tree', "state": 'CO'},
            {"name": 'HCA HEALTHONE SPALDING REHABILITATION', "city": 'Aurora', "state": 'CO'},
            {"name": 'HCA HEALTHONE AURORA', "city": 'Aurora', "state": 'CO'},
            {"name": "HCA HEALTHONE PRESBYTERIAN ST. LUKE'S", "city": 'Denver', "state": 'CO'},
            {"name": 'HCA HEALTHONE MOUNTAIN RIDGE', "city": 'Thornton', "state": 'CO'},
            {"name": 'HCA HEALTHONE ROSE', "city": 'Denver', "state": 'CO'},
            {"name": 'HCA HEALTHONE SPALDING REHAB AT PSL', "city": 'Denver', "state": 'CO'},
            {"name": 'DOCTORS HOSPITAL OF AUGUSTA', "city": 'Augusta', "state": 'GA'},
            {"name": 'MEMORIAL HEALTH MEADOWS HOSPITAL', "city": 'Vidalia', "state": 'GA'},
            {"name": 'MEMORIAL HEALTH UMC SAVANNAH', "city": 'Savannah', "state": 'GA'},
            {"name": 'GREENVIEW REGIONAL HOSPITAL', "city": 'Bowling Green', "state": 'KY'},
            {"name": 'TIMPANOGOS REGIONAL MEDICAL CTR', "city": 'Orem', "state": 'UT'},
            {"name": 'LONE PEAK HOSPITAL', "city": 'Draper', "state": 'UT'},
            {"name": 'CACHE VALLEY HOSPITAL', "city": 'North Logan', "state": 'UT'},
            {"name": 'LAKEVIEW HOSPITAL', "city": 'Bountiful', "state": 'UT'},
            {"name": 'OGDEN REGIONAL MEDICAL CENTER', "city": 'Ogden', "state": 'UT'},
            {"name": 'NORTHCREST MEDICAL CENTER', "city": 'Springfield', "state": 'TN'},
            {"name": 'MOUNTAIN VIEW HOSPITAL', "city": 'Payson', "state": 'UT'},
            {"name": 'CENTENNIAL MEDICAL CENTER AT ASHLAND CIT', "city": 'Ashland City', "state": 'TN'},
            {"name": 'BRIGHAM CITY COMMUNITY HOSPITAL', "city": 'Brigham City', "state": 'UT'},
            {"name": 'SUMMIT MEDICAL CENTER', "city": 'Hermitage', "state": 'TN'},
            {"name": 'HENDERSONVILLE MEDICAL CENTER', "city": 'Hendersonville', "state": 'TN'},
            {"name": "ST MARK'S HOSPITAL", "city": 'Salt Lake City', "state": 'UT'},
            {"name": 'HORIZON MEDICAL CENTER', "city": 'Dickson', "state": 'TN'},
            {"name": 'PARKRIDGE WEST HOSPITAL', "city": 'Jasper', "state": 'TN'},
            {"name": 'PARKRIDGE VALLEY HOSPITAL', "city": 'Chattanooga', "state": 'TN'},
            {"name": 'STONECREST MEDICAL CENTER', "city": 'Smyrna', "state": 'TN'},
            {"name": 'PARKRIDGE MEDICAL CENTER', "city": 'Chattanooga', "state": 'TN'},
            {"name": 'PARKRIDGE EAST HOSPITAL', "city": 'Chattanooga', "state": 'TN'},
            {"name": 'CENTENNIAL MEDICAL CENTER', "city": 'Nashville', "state": 'TN'},
            {"name": 'SKYLINE MEDICAL CENTER', "city": 'Nashville', "state": 'TN'},
            {"name": 'SOUTHERN HILLS MEDICAL CENTER', "city": 'Nashville', "state": 'TN'},
            {"name": 'WESLEY MEDICAL CENTER', "city": 'Wichita', "state": 'KS'},
            {"name": 'WESLEY WOODLAWN HOSPITAL & ER', "city": 'Wichita', "state": 'KS'},
            {"name": 'OVERLAND PARK REGIONAL MEDICAL CENTER', "city": 'Overland Park', "state": 'KS'},
            {"name": 'MENORAH MEDICAL CENTER', "city": 'Overland Park', "state": 'KS'},
            {"name": 'HCA HOUSTON CLEAR LAKE', "city": 'Webster', "state": 'TX'},
            {"name": 'HCA HOUSTON CONROE', "city": 'Conroe', "state": 'TX'},
            {"name": 'MEDICAL CITY ARGYLE', "city": 'Argyle', "state": 'TX'},
            {"name": 'MEDICAL CITY ARLINGTON', "city": 'Arlington', "state": 'TX'},
            {"name": 'MEDICAL CITY SURGICAL HOSPITAL ALLIANCE', "city": 'Fort Worth', "state": 'TX'},
            {"name": 'MEDICAL CITY FORT WORTH', "city": 'Fort Worth', "state": 'TX'},
            {"name": 'MEDICAL CITY MH ALLIANCE', "city": 'Fort Worth', "state": 'TX'},
            {"name": 'MEDICAL CITY ALLIANCE', "city": 'Fort Worth', "state": 'TX'},
            {"name": 'HCA HOUSTON WEST', "city": 'Houston', "state": 'TX'},
            {"name": 'TEXAS ORTHOPEDIC HOSPITAL', "city": 'Houston', "state": 'TX'},
            {"name": "WOMAN'S HOSPITAL OF TEXAS", "city": 'Houston', "state": 'TX'},
            {"name": 'HCA HOUSTON NORTHWEST', "city": 'Houston', "state": 'TX'},
            {"name": 'HCA HOUSTON MED CTR', "city": 'Houston', "state": 'TX'},
            {"name": 'THE CHRISTIE NHS JV', "city": 'Manchaster', "state": 'EN'},
            {"name": 'THE LISTER HOSPITAL', "city": 'London', "state": 'EN'},
            {"name": 'LONDON BRIDGE HOSPITAL', "city": 'London', "state": 'EN'},
            {"name": 'THE PRINCESS GRACE HOSPITAL', "city": 'London', "state": 'EN'},
            {"name": 'THE WELLINGTON PRIVATE HOSPITAL LIMITED', "city": 'London', "state": 'EN'},
            {"name": 'HCA HEALTHCARE TRIDENT HOSPITAL', "city": 'Summerville', "state": 'SC'},
        ],
    },
    {
        "company": "CommonSpirit Health",
        "source_url": "https://www.commonspirit.org/find-a-location",
        "verified_at": "2026-09-17",
        "hospitals": [
            {"name": 'CommonSpirit - Memorial Hospital - Chattanooga', "city": 'Chattanooga', "state": 'TN'},
            {"name": 'Dignity Health - Glendale Memorial Hospital and Health Center', "city": 'Glendale', "state": 'CA'},
            {"name": 'CHI Health Creighton University Medical Center - Bergan Mercy', "city": 'Omaha', "state": 'NE'},
            {"name": "St. Luke's Health - The Vintage Hospital - Houston, TX", "city": 'Houston', "state": 'TX'},
            {"name": 'St. Francis Hospital', "city": 'Federal Way', "state": 'WA'},
            {"name": 'Dignity Health - St. Bernardine Medical Center', "city": 'San Bernardino', "state": 'CA'},
            {"name": 'Dignity Health - St. Rose Dominican Hospital, San Martin Campus - Las Vegas, NV', "city": 'Las Vegas', "state": 'NV'},
            {"name": 'CHI St. Alexius Health Bismarck Medical Center', "city": 'Bismarck', "state": 'ND'},
            {"name": 'Virginia Mason Medical Center', "city": 'Seattle', "state": 'WA'},
            {"name": "CHI Health St. Mary's", "city": 'Nebraska City', "state": 'NE'},
            {"name": 'CHI St. Alexius Health Turtle Lake Hospital', "city": 'Turtle Lake', "state": 'ND'},
            {"name": 'Dignity Health - Arizona General Hospital Laveen', "city": 'Laveen', "state": 'AZ'},
            {"name": 'St. Clare Hospital', "city": 'Lakewood', "state": 'WA'},
            {"name": 'CommonSpirit St. Anthony North Hospital', "city": 'Westminster', "state": 'CO'},
            {"name": 'CommonSpirit - Saint Joseph Hospital - Berea', "city": 'Berea', "state": 'KY'},
            {"name": 'CommonSpirit Holy Cross Hospital - West Valley', "city": 'West Valley City', "state": 'UT'},
            {"name": 'CommonSpirit St. Catherine Hospital - Dodge City', "city": 'Dodge City', "state": 'KS'},
            {"name": 'CHI St. Anthony Hospital - Pendleton', "city": 'Pendleton', "state": 'OR'},
            {"name": 'CHI St. Alexius Health Dickinson Medical Center', "city": 'Dickinson', "state": 'ND'},
            {"name": 'Dignity Health - Sequoia Hospital', "city": 'Redwood City', "state": 'CA'},
            {"name": 'CHI St. Alexius Health Carrington Medical Center', "city": 'Carrington', "state": 'ND'},
            {"name": "St. Luke's Health - Memorial Hospital - Lufkin, TX", "city": 'Lufkin', "state": 'TX'},
            {"name": "Dignity Health - St. John's Hospital Camarillo", "city": 'Camarillo', "state": 'CA'},
            {"name": 'CHI Health Mercy Council Bluffs', "city": 'Council Bluffs', "state": 'IA'},
            {"name": 'CHI Health Missouri Valley', "city": 'Missouri Valley', "state": 'IA'},
            {"name": 'St. Joseph Health College Station Hospital - College Station, TX', "city": 'College Station', "state": 'TX'},
            {"name": 'CommonSpirit St. Mary-Corwin Hospital', "city": 'Pueblo', "state": 'CO'},
            {"name": 'CHI St. Vincent Hot Springs', "city": 'Hot Springs', "state": 'AR'},
            {"name": 'Trinity Medical Center East', "city": 'Steubenville', "state": 'OH'},
            {"name": 'St. Joseph Health Regional Hospital - Bryan, TX', "city": 'Bryan', "state": 'TX'},
            {"name": 'Dignity Health – Mark Twain Medical Center', "city": 'San Andreas', "state": 'CA'},
            {"name": 'St. Joseph Health Madison Hospital - Madisonville, TX', "city": 'Madisonville', "state": 'TX'},
            {"name": 'CommonSpirit St. Anthony Hospital', "city": 'Lakewood', "state": 'CO'},
            {"name": 'CommonSpirit Holy Cross Hospital - Davis', "city": 'Layton', "state": 'UT'},
            {"name": "Dignity Health St. Joseph's Westgate Medical Center", "city": 'Glendale', "state": 'AZ'},
            {"name": 'CommonSpirit St. Anthony Summit Hospital', "city": 'Frisco', "state": 'CO'},
            {"name": 'CHI Health Good Samaritan', "city": 'Kearney', "state": 'NE'},
            {"name": 'CommonSpirit Penrose Hospital', "city": 'Colorado Springs', "state": 'CO'},
            {"name": 'Dignity Health Mercy Gilbert Medical Center', "city": 'Gilbert', "state": 'AZ'},
            {"name": "St. Luke's Health - Memorial Hospital - Livingston, TX", "city": 'Livingston', "state": 'TX'},
            {"name": 'CommonSpirit - Continuing Care Hospital - Lexington', "city": 'Lexington', "state": 'KY'},
            {"name": 'Dignity Health - Sierra Nevada Memorial Hospital', "city": 'Grass Valley', "state": 'CA'},
            {"name": "Dignity Health - St. Joseph's Medical Center", "city": 'Stockton', "state": 'CA'},
            {"name": 'St. Joseph Health Burleson Hospital - Caldwell, TX', "city": 'Caldwell', "state": 'TX'},
            {"name": 'CHI LakeWood Health', "city": 'Baudette', "state": 'MN'},
            {"name": 'Dignity Health – Mercy Medical Center', "city": 'Merced', "state": 'CA'},
            {"name": 'CommonSpirit Mercy Hospital', "city": 'Durango', "state": 'CO'},
            {"name": 'CommonSpirit Bob Wilson Memorial Hospital', "city": 'Ulysses', "state": 'KS'},
            {"name": 'CHI Health St. Francis', "city": 'Grand Island', "state": 'NE'},
            {"name": "CommonSpirit - Saint Joseph Medical Center - The Women's Hospital - East Lexington", "city": 'Lexington', "state": 'KY'},
            {"name": 'Dignity Health – Mercy Medical Center Redding', "city": 'Redding', "state": 'CA'},
            {"name": 'Dignity Health - French Hospital Medical Center', "city": 'San Luis Obispo', "state": 'CA'},
            {"name": 'Dignity Health - Mercy General Hospital', "city": 'Sacramento', "state": 'CA'},
            {"name": 'CHI Mercy Health Mercy Medical Center', "city": 'Roseburg', "state": 'OR'},
            {"name": 'CommonSpirit St. Thomas More Hospital', "city": 'Canon City', "state": 'CO'},
            {"name": 'CommonSpirit - Memorial Hospital - North Georgia', "city": 'Ringgold', "state": 'GA'},
            {"name": "St. Luke's Health - Sugar Land Hospital - Sugar Land, TX", "city": 'Sugar Land', "state": 'TX'},
            {"name": 'CHI Health Nebraska Heart', "city": 'Lincoln', "state": 'NE'},
            {"name": 'CommonSpirit St. Francis Hospital - Interquest', "city": 'Colorado Springs', "state": 'CO'},
            {"name": 'St. Elizabeth Hospital', "city": 'Enumclaw', "state": 'WA'},
            {"name": 'CHI Health Schuyler', "city": 'Schuyler', "state": 'NE'},
            {"name": 'CommonSpirit Holy Cross Hospital - Jordan Valley', "city": 'West Jordan', "state": 'UT'},
            {"name": "St. Luke's Health - Lakeside Hospital - The Woodlands, TX", "city": 'The Woodlands', "state": 'TX'},
            {"name": 'Dignity Health - St. Rose Dominican Hospital, Rose de Lima Campus - Henderson, NV', "city": 'Henderson', "state": 'NV'},
            {"name": "Dignity Health St. Joseph's Hospital and Medical Center", "city": 'Phoenix', "state": 'AZ'},
            {"name": 'St. Anthony Hospital', "city": 'Gig Harbor', "state": 'WA'},
            {"name": 'Dignity Health - St. Rose Dominican Hospital, Siena Campus - Henderson, NV', "city": 'Henderson', "state": 'NV'},
            {"name": 'CommonSpirit St. Catherine Hospital - Garden City', "city": 'Garden City', "state": 'KS'},
            {"name": 'CommonSpirit Holy Cross Hospital - Mountain Point', "city": 'Lehi', "state": 'UT'},
            {"name": 'Dignity Health - St. Mary Medical Center', "city": 'Long Beach', "state": 'CA'},
            {"name": 'Dignity Health - Methodist Hospital of Sacramento', "city": 'Sacramento', "state": 'CA'},
            {"name": 'St. Joseph Health Grimes Hospital - Navasota, TX', "city": 'Navasota', "state": 'TX'},
            {"name": 'Dignity Health, Yavapai Regional Medical Center West', "city": 'Prescott', "state": 'AZ'},
            {"name": "St. Luke's Health - Memorial Hospital - San Augustine, TX", "city": 'San Augustine', "state": 'TX'},
            {"name": 'CommonSpirit - Saint Joseph Hospital - Mount Sterling', "city": 'Mount Sterling', "state": 'KY'},
            {"name": 'CHI Health Creighton University Medical Center - University Campus', "city": 'Omaha', "state": 'NE'},
            {"name": 'CHI St. Vincent Morrilton', "city": 'Morrilton', "state": 'AR'},
            {"name": "Baylor St. Luke's Medical Center - O'Quinn Medical Tower - Houston, TX", "city": 'Houston', "state": 'TX'},
            {"name": 'Dignity Health - Community Hospital of San Bernardino', "city": 'San Bernardino', "state": 'CA'},
            {"name": 'CHI Mercy Health Valley City', "city": 'Valley City', "state": 'ND'},
            {"name": 'CHI Health Immanuel', "city": 'Omaha', "state": 'NE'},
            {"name": 'CommonSpirit - Saint Joseph Hospital - Lexington', "city": 'Lexington', "state": 'KY'},
            {"name": 'CHI Health Midlands', "city": 'Papillion', "state": 'NE'},
            {"name": 'CHI St. Alexius Health Turtle Lake Clinic', "city": 'Turtle Lake', "state": 'ND'},
            {"name": 'Dignity Health - Arizona General Hospital Mesa', "city": 'Mesa', "state": 'AZ'},
            {"name": 'Dignity Health – Mercy Hospital Downtown', "city": 'Bakersfield', "state": 'CA'},
            {"name": "St. Luke's Health - Brazosport Hospital - Lake Jackson, TX", "city": 'Lake Jackson', "state": 'TX'},
            {"name": 'CHI Health Lakeside', "city": 'Omaha', "state": 'NE'},
            {"name": 'Dignity Health - Dominican Hospital', "city": 'Santa Cruz', "state": 'CA'},
            {"name": 'Dignity Health Chandler Regional Medical Center', "city": 'Chandler', "state": 'AZ'},
            {"name": 'CHI St. Vincent North', "city": 'Sherwood', "state": 'AR'},
            {"name": 'CHI Mercy Health', "city": 'Roseburg', "state": 'OR'},
            {"name": 'St. Joseph Medical Center', "city": 'Tacoma', "state": 'WA'},
            {"name": "Dignity Health - St. John's Regional Medical Center", "city": 'Oxnard', "state": 'CA'},
            {"name": 'St. Michael Medical Center', "city": 'Silverdale', "state": 'WA'},
            {"name": 'CHI Health Mercy Corning', "city": 'Corning', "state": 'IA'},
            {"name": 'Dignity Health – St. Elizabeth Community Hospital', "city": 'Red Bluff', "state": 'CA'},
            {"name": 'CHI Lisbon Health', "city": 'Lisbon', "state": 'ND'},
            {"name": 'CHI Franciscan Rehabilitation Hospital', "city": 'Tacoma', "state": 'WA'},
            {"name": 'CHI Health St. Elizabeth', "city": 'Lincoln', "state": 'NE'},
            {"name": 'Dignity Health - Mercy San Juan Medical Center', "city": 'Carmichael', "state": 'CA'},
            {"name": 'CHI Health Plainview', "city": 'Plainview', "state": 'NE'},
            {"name": 'CHI St. Vincent Infirmary', "city": 'Little Rock', "state": 'AR'},
            {"name": "CHI St. Gabriel's Hospital", "city": 'Little Falls', "state": 'MN'},
            {"name": 'Dignity Health - California Hospital Medical Center', "city": 'Los Angeles', "state": 'CA'},
            {"name": 'Dignity Health – Mercy Medical Center Mt. Shasta', "city": 'Mount Shasta', "state": 'CA'},
            {"name": 'CommonSpirit - Saint Joseph Medical Center - East Lexington', "city": 'Lexington', "state": 'KY'},
            {"name": "St. Luke's Health - Springwoods Village Hospital - Spring, TX", "city": 'Spring', "state": 'TX'},
            {"name": 'CommonSpirit Longmont United Hospital', "city": 'Longmont', "state": 'CO'},
            {"name": 'CommonSpirit - Saint Joseph Hospital - Bardstown', "city": 'Bardstown', "state": 'KY'},
            {"name": 'Dignity Health - Marian Regional Medical Center', "city": 'Santa Maria', "state": 'CA'},
            {"name": "Baylor St. Luke's Medical Center - Houston, TX", "city": 'Houston', "state": 'TX'},
            {"name": 'Dignity Health - Mercy Hospital of Folsom', "city": 'Folsom', "state": 'CA'},
            {"name": 'Dignity Health - Northridge Hospital Medical Center', "city": 'Northridge', "state": 'CA'},
            {"name": 'Dignity Health – Memorial Hospital', "city": 'Bakersfield', "state": 'CA'},
            {"name": "Baylor St. Luke's Medical Center - McNair Campus - Houston, TX", "city": 'Houston', "state": 'TX'},
            {"name": "St. Luke's Health - The Woodlands Hospital - The Woodlands, TX", "city": 'The Woodlands', "state": 'TX'},
            {"name": 'CommonSpirit - Saint Joseph Hospital - London', "city": 'London', "state": 'KY'},
            {"name": 'CommonSpirit St. Francis Hospital', "city": 'Colorado Springs', "state": 'CO'},
            {"name": 'CommonSpirit St. Elizabeth Hospital', "city": 'Fort Morgan', "state": 'CO'},
            {"name": 'CHI St. Alexius Health Garrison Memorial Hospital', "city": 'Garrison', "state": 'ND'},
            {"name": 'Dignity Health, Yavapai Regional Medical Center East', "city": 'Prescott Valley', "state": 'AZ'},
            {"name": 'Dignity Health - Mercy Hospital Southwest', "city": 'Bakersfield', "state": 'CA'},
            {"name": "St. Luke's Health - Patients Medical Center - Pasadena, TX", "city": 'Pasadena', "state": 'TX'},
            {"name": "CHI St. Joseph's Health", "city": 'Park Rapids', "state": 'MN'},
            {"name": 'Dignity Health - Arroyo Grande Community Hospital', "city": 'Arroyo Grande', "state": 'CA'},
            {"name": 'St. Anne Hospital', "city": 'Burien', "state": 'WA'},
            {"name": 'Dignity Health - Woodland Memorial Hospital', "city": 'Woodland', "state": 'CA'},
            {"name": 'Wellfound Behavioral Health Hospital', "city": 'Tacoma', "state": 'WA'},
            {"name": 'CommonSpirit Holy Cross Hospital - Salt Lake', "city": 'Salt Lake City', "state": 'UT'},
        ],
    },
]
