"""Curated roster of hospitals by parent health-system operator, used to tag
individual HIFLD live-map facilities with "part of <Operator>" where a match is
found. A snapshot, not live data — see the "How this data stays current" note in
README.md. Matching is done client-side (static/app.js) against the live HIFLD
facility feed by normalized name + city + state; a HIFLD hospital with no match
here is shown as "Parent operator not identified," never guessed.

Extend this the same way as health_systems_data.py: one HOSPITAL_ROSTERS entry
per company, each hospital row sourced from that company's own official location
directory (cited in source_url), with a verified_at date.
"""

HOSPITAL_ROSTERS = [
    {
        "company": "HCA Healthcare",
        "source_url": "https://www.hcahealthcare.com/locations/",
        "verified_at": "2026-09-17",
        "hospitals": [
            {"name": "LEE'S SUMMIT MEDICAL CENTER", "city": 'Lees Summit', "state": 'MO'},
            {"name": 'RESEARCH MEDICAL CENTER', "city": 'Kansas City', "state": 'MO'},
            {"name": 'LAFAYETTE REGIONAL HEALTH CENTER', "city": 'Lexington', "state": 'MO'},
            {"name": 'BELTON REGIONAL MEDICAL CENTER', "city": 'Belton', "state": 'MO'},
            {"name": 'CENTERPOINT MEDICAL CENTER', "city": 'Independence', "state": 'MO'},
            {"name": 'BLUE RIDGE REGIONAL HOSPITAL', "city": 'Spruce Pine', "state": 'NC'},
            {"name": 'TRANSYLVANIA REGIONAL HOSPITAL', "city": 'Brevard', "state": 'NC'},
            {"name": 'ANGEL MEDICAL CENTER', "city": 'Franklin', "state": 'NC'},
            {"name": 'MCDOWELL HOSPITAL', "city": 'Marion', "state": 'NC'},
            {"name": 'HIGHLANDS-CASHIERS HOSPITAL', "city": 'Highlands', "state": 'NC'},
            {"name": 'MISSION HOSPITAL', "city": 'Asheville', "state": 'NC'},
            {"name": 'CAREPARTNERS REHABILITATION HOSPITAL', "city": 'Asheville', "state": 'NC'},
            {"name": 'HCA FLORIDA ST. LUCIE HOSPITAL', "city": 'Port St Lucie', "state": 'FL'},
            {"name": 'HCA FLORIDA AVENTURA HOSPITAL', "city": 'Aventura', "state": 'FL'},
            {"name": 'HCA FLORIDA WOODMONT HOSPITAL', "city": 'Tamarac', "state": 'FL'},
            {"name": 'HCA FLORIDA TWIN CITIES HOSPITAL', "city": 'Niceville', "state": 'FL'},
            {"name": 'HCA FLORIDA LAWNWOOD HOSPITAL', "city": 'Fort Pierce', "state": 'FL'},
            {"name": 'HCA FLORIDA LAKE MONROE HOSPITAL', "city": 'Sanford', "state": 'FL'},
            {"name": 'HCA FLORIDA WEST HOSPITAL', "city": 'Pensacola', "state": 'FL'},
            {"name": 'HCA FLORIDA OAK HILL HOSPITAL', "city": 'Brooksville', "state": 'FL'},
            {"name": 'HCA FLORIDA BRANDON HOSPITAL', "city": 'Brandon', "state": 'FL'},
            {"name": 'UCF LAKE NONA HOSPITAL', "city": 'Orlando', "state": 'FL'},
            {"name": 'HCA FLORIDA CAPITAL HOSPITAL', "city": 'Tallahassee', "state": 'FL'},
            {"name": 'HCA FLORIDA JFK NORTH HOSPITAL', "city": 'West Palm Beach', "state": 'FL'},
            {"name": 'HCA FLORIDA PALMS WEST HOSPITAL', "city": 'Loxahatchee', "state": 'FL'},
            {"name": 'HCA FLORIDA LAKE CITY HOSPITAL', "city": 'Lake City', "state": 'FL'},
            {"name": 'HCA FLORIDA NORTH FLORIDA HOSPITAL', "city": 'Gainesville', "state": 'FL'},
            {"name": 'HCA FLORIDA RAULERSON HOSPITAL', "city": 'Okeechobee', "state": 'FL'},
            {"name": 'HCA FLORIDA MEMORIAL HOSPITAL', "city": 'Jacksonville', "state": 'FL'},
            {"name": 'HCA FLORIDA GULF COAST HOSPITAL', "city": 'Panama City', "state": 'FL'},
            {"name": 'HCA FLORIDA JFK HOSPITAL', "city": 'Atlantis', "state": 'FL'},
            {"name": 'HCA FLORIDA KENDALL HOSPITAL', "city": 'Miami', "state": 'FL'},
            {"name": 'HCA FLORIDA MERCY HOSPITAL', "city": 'Miami', "state": 'FL'},
            {"name": 'HCA FLORIDA TRINITY HOSPITAL', "city": 'Trinity', "state": 'FL'},
            {"name": 'HCA FLORIDA NORTHWEST HOSPITAL', "city": 'Margate', "state": 'FL'},
            {"name": 'HCA FLORIDA ENGLEWOOD HOSPITAL', "city": 'Englewood', "state": 'FL'},
            {"name": 'HCA FLORIDA ORANGE PARK HOSPITAL', "city": 'Orange Park', "state": 'FL'},
            {"name": 'HCA FLORIDA - OCALA HOSPITAL', "city": 'Ocala', "state": 'FL'},
            {"name": 'HCA FLORIDA WEST MARION HOSPITAL', "city": 'Ocala', "state": 'FL'},
            {"name": 'OVIEDO MEDICAL CENTER', "city": 'Oviedo', "state": 'FL'},
            {"name": 'HCA FLORIDA LEHIGH HOSPITAL', "city": 'Lehigh Acres', "state": 'FL'},
            {"name": 'HCA FLORIDA WESTSIDE HOSPITAL', "city": 'Plantation', "state": 'FL'},
            {"name": 'HCA FLORIDA SARASOTA DOCTORS HOSPITAL', "city": 'Sarasota', "state": 'FL'},
            {"name": 'HCA FLORIDA FORT WALTON-DESTIN HOSPITAL', "city": 'Fort Walton Beach', "state": 'FL'},
            {"name": 'HCA FLORIDA WEST TAMPA HOSPITAL', "city": 'Tampa', "state": 'FL'},
            {"name": 'HCA FLORIDA SOUTH TAMPA HOSPITAL', "city": 'Tampa', "state": 'FL'},
            {"name": 'HCA FLORIDA OSCEOLA HOSPITAL', "city": 'Kissimmee', "state": 'FL'},
            {"name": 'HCA FLORIDA POINCIANA HOSPITAL', "city": 'Kissimmee', "state": 'FL'},
            {"name": 'HCA FLORIDA BAYONET POINT HOSPITAL', "city": 'Hudson', "state": 'FL'},
            {"name": 'HCA FLORIDA UNIVERSITY HOSPITAL', "city": 'Davie', "state": 'FL'},
            {"name": 'HCA FLORIDA NORTHSIDE HOSPITAL', "city": 'St Petersburg', "state": 'FL'},
            {"name": 'HCA FLORIDA ST. PETERSBURG HOSPITAL', "city": 'St Petersburg', "state": 'FL'},
            {"name": 'HCA FLORIDA SOUTH SHORE HOSPITAL', "city": 'Sun City Center', "state": 'FL'},
            {"name": 'HCA FLORIDA LARGO WEST HOSPITAL', "city": 'Largo', "state": 'FL'},
            {"name": 'HCA FLORIDA LARGO HOSPITAL', "city": 'Largo', "state": 'FL'},
            {"name": 'HCA FLORIDA CITRUS HOSPITAL', "city": 'Inverness', "state": 'FL'},
            {"name": 'HCA FLORIDA PUTNAM HOSPITAL', "city": 'Palatka', "state": 'FL'},
            {"name": 'HCA FLORIDA HIGHLANDS HOSPITAL', "city": 'Sebring', "state": 'FL'},
            {"name": 'HCA FLORIDA FAWCETT HOSPITAL', "city": 'Port Charlotte', "state": 'FL'},
            {"name": 'HCA FLORIDA BLAKE HOSPITAL', "city": 'Bradenton', "state": 'FL'},
            {"name": 'ALASKA REGIONAL HOSPITAL', "city": 'Anchorage', "state": 'AK'},
            {"name": 'RAPIDES REGIONAL MEDICAL CENTER', "city": 'Alexandria', "state": 'LA'},
            {"name": 'EASTERN IDAHO RMC', "city": 'Idaho Falls', "state": 'ID'},
            {"name": 'WEST VALLEY MEDICAL CENTER', "city": 'Caldwell', "state": 'ID'},
            {"name": 'FRISBIE MEMORIAL HOSPITAL', "city": 'Rochester', "state": 'NH'},
            {"name": 'PORTSMOUTH REGIONAL HOSPITAL', "city": 'Portsmouth', "state": 'NH'},
            {"name": 'PARKLAND MEDICAL CENTER', "city": 'Derry', "state": 'NH'},
            {"name": 'CATHOLIC MEDICAL CENTER', "city": 'Manchester', "state": 'NH'},
            {"name": 'LEWISGALE HOSPITAL-MONTGOMERY', "city": 'Blacksburg', "state": 'VA'},
            {"name": 'SPOTSYLVANIA REGIONAL MEDICAL CENTER', "city": 'Fredericksburg', "state": 'VA'},
            {"name": 'JOHNSTON-WILLIS HOSPITAL', "city": 'Richmond', "state": 'VA'},
            {"name": 'CHIPPENHAM HOSPITAL', "city": 'Richmond', "state": 'VA'},
            {"name": 'RETREAT DOCTORS HOSPITAL', "city": 'Richmond', "state": 'VA'},
            {"name": 'HENRICO DOCTORS HOSPITAL - FOREST', "city": 'Richmond', "state": 'VA'},
            {"name": 'PARHAM DOCTORS HOSPITAL', "city": 'Richmond', "state": 'VA'},
            {"name": 'LEWISGALE MEDICAL CENTER', "city": 'Salem', "state": 'VA'},
            {"name": 'STONESPRINGS HOSPITAL CENTER', "city": 'Sterling', "state": 'VA'},
            {"name": 'RESTON HOSPITAL CENTER', "city": 'Reston', "state": 'VA'},
            {"name": 'TRICITIES HOSPITAL', "city": 'Hopewell', "state": 'VA'},
            {"name": 'LEWISGALE HOSPITAL-ALLEGHANY', "city": 'Low Moor', "state": 'VA'},
            {"name": 'LEWISGALE HOSPITAL-PULASKI', "city": 'Pulaski', "state": 'VA'},
            {"name": 'ROUND ROCK MEDICAL CENTER', "city": 'Round Rock', "state": 'TX'},
            {"name": 'MEDICAL CITY LAS COLINAS', "city": 'Irving', "state": 'TX'},
            {"name": 'HCA HOUSTON PEARLAND', "city": 'Pearland', "state": 'TX'},
            {"name": 'MEDICAL CITY NORTH HILLS', "city": 'North Richland Hills', "state": 'TX'},
            {"name": 'VALLEY REGIONAL MEDICAL CENTER', "city": 'Brownsville', "state": 'TX'},
            {"name": 'METHODIST HOSPITAL ATASCOSA', "city": 'Jourdanton', "state": 'TX'},
            {"name": 'MEDICAL CITY PLANO', "city": 'Plano', "state": 'TX'},
            {"name": 'HEART HOSPITAL OF AUSTIN', "city": 'Austin', "state": 'TX'},
            {"name": 'SOUTH AUSTIN MEDICAL CENTER', "city": 'Austin', "state": 'TX'},
            {"name": 'NORTH AUSTIN MEDICAL CENTER', "city": 'Austin', "state": 'TX'},
            {"name": "ST DAVID'S MEDICAL CENTER", "city": 'Austin', "state": 'TX'},
            {"name": "ST. DAVID'S SURGICAL HOSPITAL", "city": 'Austin', "state": 'TX'},
            {"name": 'HCA HOUSTON MAINLAND', "city": 'Texas City', "state": 'TX'},
            {"name": 'MEDICAL CITY LEWISVILLE', "city": 'Lewisville', "state": 'TX'},
            {"name": 'MEDICAL CITY SACHSE', "city": 'Sachse', "state": 'TX'},
            {"name": 'RIO GRANDE REGIONAL HOSPITAL', "city": 'McAllen', "state": 'TX'},
            {"name": 'METHODIST HOSPITAL HILL COUNTRY', "city": 'Fredericksburg', "state": 'TX'},
            {"name": 'METHODIST HOSPITAL', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METHODIST HOSPITAL LANDMARK', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METHODIST TEXSAN HOSPITAL', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METHODIST SPECIALTY & TRANSPLANT HOSP', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METHODIST REHABILITATION HOSPITAL TEXSAN', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METHODIST HOSPITAL WESTOVER HILLS', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METHODIST HOSPITAL STONE OAK', "city": 'San Antonio', "state": 'TX'},
            {"name": 'METROPOLITAN METHODIST HOSPITAL', "city": 'San Antonio', "state": 'TX'},
            {"name": 'MEDICAL CITY WEATHERFORD', "city": 'Weatherford', "state": 'TX'},
            {"name": 'MEDICAL CITY MH FRISCO', "city": 'Frisco', "state": 'TX'},
            {"name": 'MEDICAL CITY FRISCO', "city": 'Frisco', "state": 'TX'},
            {"name": 'HCA HOUSTON SOUTHEAST', "city": 'Pasadena', "state": 'TX'},
            {"name": 'LAS PALMAS MEDICAL CENTER', "city": 'El Paso', "state": 'TX'},
            {"name": 'DEL SOL MEDICAL CENTER', "city": 'El Paso', "state": 'TX'},
            {"name": 'MEDICAL CITY GREEN OAKS HOSPITAL DALLAS', "city": 'Dallas', "state": 'TX'},
            {"name": 'MEDICAL CITY HEART & SPINE', "city": 'Dallas', "state": 'TX'},
            {"name": 'MEDICAL CITY DALLAS', "city": 'Dallas', "state": 'TX'},
            {"name": 'HCA HOUSTON TOMBALL', "city": 'Tomball', "state": 'TX'},
            {"name": 'MEDICAL CITY DECATUR', "city": 'Decatur', "state": 'TX'},
            {"name": 'NORTHEAST METHODIST HOSPITAL', "city": 'Live Oak', "state": 'TX'},
            {"name": 'HCA HOUSTON N CYPRESS', "city": 'Cypress', "state": 'TX'},
            {"name": 'MEDICAL CITY DENTON', "city": 'Denton', "state": 'TX'},
            {"name": 'MEDICAL CITY MCKINNEY', "city": 'McKinney', "state": 'TX'},
            {"name": 'HCA HOUSTON KINGWOOD', "city": 'Kingwood', "state": 'TX'},
            {"name": "ST. DAVID'S GEORGETOWN", "city": 'Georgetown', "state": 'TX'},
            {"name": 'CORPUS CHRISTI MEDICAL CENTER', "city": 'Corpus Christi', "state": 'TX'},
            {"name": 'LOC AT UCLH - GBP', "city": 'London', "state": 'EN'},
            {"name": 'HARLEY STREET CLINIC', "city": 'London', "state": 'EN'},
            {"name": 'THE HARBORNE HOSPITAL', "city": 'Birmingham', "state": 'EN'},
            {"name": 'THE PORTLAND HOSPITAL', "city": 'London', "state": 'EN'},
            {"name": 'GRAND STRAND MEDICAL CENTER', "city": 'Myrtle Beach', "state": 'SC'},
            {"name": 'HCA HEALTHCARE COLLETON HOSPITAL', "city": 'Walterboro', "state": 'SC'},
            {"name": 'HCA HEALTHCARE TRIDENT HOSPITAL', "city": 'Charleston', "state": 'SC'},
            {"name": 'GOOD SAMARITAN HOSPITAL', "city": 'Los Gatos', "state": 'CA'},
            {"name": 'GOOD SAMARITAN HOSPITAL', "city": 'San Jose', "state": 'CA'},
            {"name": 'LOS ROBLES HOSPITAL AND MEDICAL CENTER', "city": 'Thousand Oaks', "state": 'CA'},
            {"name": 'LOS ROBLES HOSPITAL AND MEDICAL CENTER', "city": 'West Lake Village', "state": 'CA'},
            {"name": 'RIVERSIDE COMMUNITY HOSPITAL', "city": 'Riverside', "state": 'CA'},
            {"name": 'MOUNTAINVIEW HOSPITAL', "city": 'Las Vegas', "state": 'NV'},
            {"name": 'SOUTHERN HILLS HOSP & MED CTR-LAS VEGAS', "city": 'Las Vegas', "state": 'NV'},
            {"name": 'SUNRISE HOSPITAL AND MEDICAL CENTER', "city": 'Las Vegas', "state": 'NV'},
            {"name": 'HCA HEALTHONE SWEDISH', "city": 'Englewood', "state": 'CO'},
            {"name": 'HCA HEALTHONE SKY RIDGE', "city": 'Lone Tree', "state": 'CO'},
            {"name": 'HCA HEALTHONE SPALDING REHABILITATION', "city": 'Aurora', "state": 'CO'},
            {"name": 'HCA HEALTHONE AURORA', "city": 'Aurora', "state": 'CO'},
            {"name": "HCA HEALTHONE PRESBYTERIAN ST. LUKE'S", "city": 'Denver', "state": 'CO'},
            {"name": 'HCA HEALTHONE MOUNTAIN RIDGE', "city": 'Thornton', "state": 'CO'},
            {"name": 'HCA HEALTHONE ROSE', "city": 'Denver', "state": 'CO'},
            {"name": 'HCA HEALTHONE SPALDING REHAB AT PSL', "city": 'Denver', "state": 'CO'},
            {"name": 'DOCTORS HOSPITAL OF AUGUSTA', "city": 'Augusta', "state": 'GA'},
            {"name": 'MEMORIAL HEALTH MEADOWS HOSPITAL', "city": 'Vidalia', "state": 'GA'},
            {"name": 'MEMORIAL HEALTH UMC SAVANNAH', "city": 'Savannah', "state": 'GA'},
            {"name": 'GREENVIEW REGIONAL HOSPITAL', "city": 'Bowling Green', "state": 'KY'},
            {"name": 'TIMPANOGOS REGIONAL MEDICAL CTR', "city": 'Orem', "state": 'UT'},
            {"name": 'LONE PEAK HOSPITAL', "city": 'Draper', "state": 'UT'},
            {"name": 'CACHE VALLEY HOSPITAL', "city": 'North Logan', "state": 'UT'},
            {"name": 'LAKEVIEW HOSPITAL', "city": 'Bountiful', "state": 'UT'},
            {"name": 'OGDEN REGIONAL MEDICAL CENTER', "city": 'Ogden', "state": 'UT'},
            {"name": 'NORTHCREST MEDICAL CENTER', "city": 'Springfield', "state": 'TN'},
            {"name": 'MOUNTAIN VIEW HOSPITAL', "city": 'Payson', "state": 'UT'},
            {"name": 'CENTENNIAL MEDICAL CENTER AT ASHLAND CIT', "city": 'Ashland City', "state": 'TN'},
            {"name": 'BRIGHAM CITY COMMUNITY HOSPITAL', "city": 'Brigham City', "state": 'UT'},
            {"name": 'SUMMIT MEDICAL CENTER', "city": 'Hermitage', "state": 'TN'},
            {"name": 'HENDERSONVILLE MEDICAL CENTER', "city": 'Hendersonville', "state": 'TN'},
            {"name": "ST MARK'S HOSPITAL", "city": 'Salt Lake City', "state": 'UT'},
            {"name": 'HORIZON MEDICAL CENTER', "city": 'Dickson', "state": 'TN'},
            {"name": 'PARKRIDGE WEST HOSPITAL', "city": 'Jasper', "state": 'TN'},
            {"name": 'PARKRIDGE VALLEY HOSPITAL', "city": 'Chattanooga', "state": 'TN'},
            {"name": 'STONECREST MEDICAL CENTER', "city": 'Smyrna', "state": 'TN'},
            {"name": 'PARKRIDGE MEDICAL CENTER', "city": 'Chattanooga', "state": 'TN'},
            {"name": 'PARKRIDGE EAST HOSPITAL', "city": 'Chattanooga', "state": 'TN'},
            {"name": 'CENTENNIAL MEDICAL CENTER', "city": 'Nashville', "state": 'TN'},
            {"name": 'SKYLINE MEDICAL CENTER', "city": 'Nashville', "state": 'TN'},
            {"name": 'SOUTHERN HILLS MEDICAL CENTER', "city": 'Nashville', "state": 'TN'},
            {"name": 'WESLEY MEDICAL CENTER', "city": 'Wichita', "state": 'KS'},
            {"name": 'WESLEY WOODLAWN HOSPITAL & ER', "city": 'Wichita', "state": 'KS'},
            {"name": 'OVERLAND PARK REGIONAL MEDICAL CENTER', "city": 'Overland Park', "state": 'KS'},
            {"name": 'MENORAH MEDICAL CENTER', "city": 'Overland Park', "state": 'KS'},
            {"name": 'HCA HOUSTON CLEAR LAKE', "city": 'Webster', "state": 'TX'},
            {"name": 'HCA HOUSTON CONROE', "city": 'Conroe', "state": 'TX'},
            {"name": 'MEDICAL CITY ARGYLE', "city": 'Argyle', "state": 'TX'},
            {"name": 'MEDICAL CITY ARLINGTON', "city": 'Arlington', "state": 'TX'},
            {"name": 'MEDICAL CITY SURGICAL HOSPITAL ALLIANCE', "city": 'Fort Worth', "state": 'TX'},
            {"name": 'MEDICAL CITY FORT WORTH', "city": 'Fort Worth', "state": 'TX'},
            {"name": 'MEDICAL CITY MH ALLIANCE', "city": 'Fort Worth', "state": 'TX'},
            {"name": 'MEDICAL CITY ALLIANCE', "city": 'Fort Worth', "state": 'TX'},
            {"name": 'HCA HOUSTON WEST', "city": 'Houston', "state": 'TX'},
            {"name": 'TEXAS ORTHOPEDIC HOSPITAL', "city": 'Houston', "state": 'TX'},
            {"name": "WOMAN'S HOSPITAL OF TEXAS", "city": 'Houston', "state": 'TX'},
            {"name": 'HCA HOUSTON NORTHWEST', "city": 'Houston', "state": 'TX'},
            {"name": 'HCA HOUSTON MED CTR', "city": 'Houston', "state": 'TX'},
            {"name": 'THE CHRISTIE NHS JV', "city": 'Manchaster', "state": 'EN'},
            {"name": 'THE LISTER HOSPITAL', "city": 'London', "state": 'EN'},
            {"name": 'LONDON BRIDGE HOSPITAL', "city": 'London', "state": 'EN'},
            {"name": 'THE PRINCESS GRACE HOSPITAL', "city": 'London', "state": 'EN'},
            {"name": 'THE WELLINGTON PRIVATE HOSPITAL LIMITED', "city": 'London', "state": 'EN'},
            {"name": 'HCA HEALTHCARE TRIDENT HOSPITAL', "city": 'Summerville', "state": 'SC'},
        ],
    },
    {
        "company": "CommonSpirit Health",
        "source_url": "https://www.commonspirit.org/find-a-location",
        "verified_at": "2026-09-17",
        "hospitals": [
            {"name": 'CommonSpirit - Memorial Hospital - Chattanooga', "city": 'Chattanooga', "state": 'TN'},
            {"name": 'Dignity Health - Glendale Memorial Hospital and Health Center', "city": 'Glendale', "state": 'CA'},
            {"name": 'CHI Health Creighton University Medical Center - Bergan Mercy', "city": 'Omaha', "state": 'NE'},
            {"name": "St. Luke's Health - The Vintage Hospital - Houston, TX", "city": 'Houston', "state": 'TX'},
            {"name": 'St. Francis Hospital', "city": 'Federal Way', "state": 'WA'},
            {"name": 'Dignity Health - St. Bernardine Medical Center', "city": 'San Bernardino', "state": 'CA'},
            {"name": 'Dignity Health - St. Rose Dominican Hospital, San Martin Campus - Las Vegas, NV', "city": 'Las Vegas', "state": 'NV'},
            {"name": 'CHI St. Alexius Health Bismarck Medical Center', "city": 'Bismarck', "state": 'ND'},
            {"name": 'Virginia Mason Medical Center', "city": 'Seattle', "state": 'WA'},
            {"name": "CHI Health St. Mary's", "city": 'Nebraska City', "state": 'NE'},
            {"name": 'CHI St. Alexius Health Turtle Lake Hospital', "city": 'Turtle Lake', "state": 'ND'},
            {"name": 'Dignity Health - Arizona General Hospital Laveen', "city": 'Laveen', "state": 'AZ'},
            {"name": 'St. Clare Hospital', "city": 'Lakewood', "state": 'WA'},
            {"name": 'CommonSpirit St. Anthony North Hospital', "city": 'Westminster', "state": 'CO'},
            {"name": 'CommonSpirit - Saint Joseph Hospital - Berea', "city": 'Berea', "state": 'KY'},
            {"name": 'CommonSpirit Holy Cross Hospital - West Valley', "city": 'West Valley City', "state": 'UT'},
            {"name": 'CommonSpirit St. Catherine Hospital - Dodge City', "city": 'Dodge City', "state": 'KS'},
            {"name": 'CHI St. Anthony Hospital - Pendleton', "city": 'Pendleton', "state": 'OR'},
            {"name": 'CHI St. Alexius Health Dickinson Medical Center', "city": 'Dickinson', "state": 'ND'},
            {"name": 'Dignity Health - Sequoia Hospital', "city": 'Redwood City', "state": 'CA'},
            {"name": 'CHI St. Alexius Health Carrington Medical Center', "city": 'Carrington', "state": 'ND'},
            {"name": "St. Luke's Health - Memorial Hospital - Lufkin, TX", "city": 'Lufkin', "state": 'TX'},
            {"name": "Dignity Health - St. John's Hospital Camarillo", "city": 'Camarillo', "state": 'CA'},
            {"name": 'CHI Health Mercy Council Bluffs', "city": 'Council Bluffs', "state": 'IA'},
            {"name": 'CHI Health Missouri Valley', "city": 'Missouri Valley', "state": 'IA'},
            {"name": 'St. Joseph Health College Station Hospital - College Station, TX', "city": 'College Station', "state": 'TX'},
            {"name": 'CommonSpirit St. Mary-Corwin Hospital', "city": 'Pueblo', "state": 'CO'},
            {"name": 'CHI St. Vincent Hot Springs', "city": 'Hot Springs', "state": 'AR'},
            {"name": 'Trinity Medical Center East', "city": 'Steubenville', "state": 'OH'},
            {"name": 'St. Joseph Health Regional Hospital - Bryan, TX', "city": 'Bryan', "state": 'TX'},
            {"name": 'Dignity Health – Mark Twain Medical Center', "city": 'San Andreas', "state": 'CA'},
            {"name": 'St. Joseph Health Madison Hospital - Madisonville, TX', "city": 'Madisonville', "state": 'TX'},
            {"name": 'CommonSpirit St. Anthony Hospital', "city": 'Lakewood', "state": 'CO'},
            {"name": 'CommonSpirit Holy Cross Hospital - Davis', "city": 'Layton', "state": 'UT'},
            {"name": "Dignity Health St. Joseph's Westgate Medical Center", "city": 'Glendale', "state": 'AZ'},
            {"name": 'CommonSpirit St. Anthony Summit Hospital', "city": 'Frisco', "state": 'CO'},
            {"name": 'CHI Health Good Samaritan', "city": 'Kearney', "state": 'NE'},
            {"name": 'CommonSpirit Penrose Hospital', "city": 'Colorado Springs', "state": 'CO'},
            {"name": 'Dignity Health Mercy Gilbert Medical Center', "city": 'Gilbert', "state": 'AZ'},
            {"name": "St. Luke's Health - Memorial Hospital - Livingston, TX", "city": 'Livingston', "state": 'TX'},
            {"name": 'CommonSpirit - Continuing Care Hospital - Lexington', "city": 'Lexington', "state": 'KY'},
            {"name": 'Dignity Health - Sierra Nevada Memorial Hospital', "city": 'Grass Valley', "state": 'CA'},
            {"name": "Dignity Health - St. Joseph's Medical Center", "city": 'Stockton', "state": 'CA'},
            {"name": 'St. Joseph Health Burleson Hospital - Caldwell, TX', "city": 'Caldwell', "state": 'TX'},
            {"name": 'CHI LakeWood Health', "city": 'Baudette', "state": 'MN'},
            {"name": 'Dignity Health – Mercy Medical Center', "city": 'Merced', "state": 'CA'},
            {"name": 'CommonSpirit Mercy Hospital', "city": 'Durango', "state": 'CO'},
            {"name": 'CommonSpirit Bob Wilson Memorial Hospital', "city": 'Ulysses', "state": 'KS'},
            {"name": 'CHI Health St. Francis', "city": 'Grand Island', "state": 'NE'},
            {"name": "CommonSpirit - Saint Joseph Medical Center - The Women's Hospital - East Lexington", "city": 'Lexington', "state": 'KY'},
            {"name": 'Dignity Health – Mercy Medical Center Redding', "city": 'Redding', "state": 'CA'},
            {"name": 'Dignity Health - French Hospital Medical Center', "city": 'San Luis Obispo', "state": 'CA'},
            {"name": 'Dignity Health - Mercy General Hospital', "city": 'Sacramento', "state": 'CA'},
            {"name": 'CHI Mercy Health Mercy Medical Center', "city": 'Roseburg', "state": 'OR'},
            {"name": 'CommonSpirit St. Thomas More Hospital', "city": 'Canon City', "state": 'CO'},
            {"name": 'CommonSpirit - Memorial Hospital - North Georgia', "city": 'Ringgold', "state": 'GA'},
            {"name": "St. Luke's Health - Sugar Land Hospital - Sugar Land, TX", "city": 'Sugar Land', "state": 'TX'},
            {"name": 'CHI Health Nebraska Heart', "city": 'Lincoln', "state": 'NE'},
            {"name": 'CommonSpirit St. Francis Hospital - Interquest', "city": 'Colorado Springs', "state": 'CO'},
            {"name": 'St. Elizabeth Hospital', "city": 'Enumclaw', "state": 'WA'},
            {"name": 'CHI Health Schuyler', "city": 'Schuyler', "state": 'NE'},
            {"name": 'CommonSpirit Holy Cross Hospital - Jordan Valley', "city": 'West Jordan', "state": 'UT'},
            {"name": "St. Luke's Health - Lakeside Hospital - The Woodlands, TX", "city": 'The Woodlands', "state": 'TX'},
            {"name": 'Dignity Health - St. Rose Dominican Hospital, Rose de Lima Campus - Henderson, NV', "city": 'Henderson', "state": 'NV'},
            {"name": "Dignity Health St. Joseph's Hospital and Medical Center", "city": 'Phoenix', "state": 'AZ'},
            {"name": 'St. Anthony Hospital', "city": 'Gig Harbor', "state": 'WA'},
            {"name": 'Dignity Health - St. Rose Dominican Hospital, Siena Campus - Henderson, NV', "city": 'Henderson', "state": 'NV'},
            {"name": 'CommonSpirit St. Catherine Hospital - Garden City', "city": 'Garden City', "state": 'KS'},
            {"name": 'CommonSpirit Holy Cross Hospital - Mountain Point', "city": 'Lehi', "state": 'UT'},
            {"name": 'Dignity Health - St. Mary Medical Center', "city": 'Long Beach', "state": 'CA'},
            {"name": 'Dignity Health - Methodist Hospital of Sacramento', "city": 'Sacramento', "state": 'CA'},
            {"name": 'St. Joseph Health Grimes Hospital - Navasota, TX', "city": 'Navasota', "state": 'TX'},
            {"name": 'Dignity Health, Yavapai Regional Medical Center West', "city": 'Prescott', "state": 'AZ'},
            {"name": "St. Luke's Health - Memorial Hospital - San Augustine, TX", "city": 'San Augustine', "state": 'TX'},
            {"name": 'CommonSpirit - Saint Joseph Hospital - Mount Sterling', "city": 'Mount Sterling', "state": 'KY'},
            {"name": 'CHI Health Creighton University Medical Center - University Campus', "city": 'Omaha', "state": 'NE'},
            {"name": 'CHI St. Vincent Morrilton', "city": 'Morrilton', "state": 'AR'},
            {"name": "Baylor St. Luke's Medical Center - O'Quinn Medical Tower - Houston, TX", "city": 'Houston', "state": 'TX'},
            {"name": 'Dignity Health - Community Hospital of San Bernardino', "city": 'San Bernardino', "state": 'CA'},
            {"name": 'CHI Mercy Health Valley City', "city": 'Valley City', "state": 'ND'},
            {"name": 'CHI Health Immanuel', "city": 'Omaha', "state": 'NE'},
            {"name": 'CommonSpirit - Saint Joseph Hospital - Lexington', "city": 'Lexington', "state": 'KY'},
            {"name": 'CHI Health Midlands', "city": 'Papillion', "state": 'NE'},
            {"name": 'CHI St. Alexius Health Turtle Lake Clinic', "city": 'Turtle Lake', "state": 'ND'},
            {"name": 'Dignity Health - Arizona General Hospital Mesa', "city": 'Mesa', "state": 'AZ'},
            {"name": 'Dignity Health – Mercy Hospital Downtown', "city": 'Bakersfield', "state": 'CA'},
            {"name": "St. Luke's Health - Brazosport Hospital - Lake Jackson, TX", "city": 'Lake Jackson', "state": 'TX'},
            {"name": 'CHI Health Lakeside', "city": 'Omaha', "state": 'NE'},
            {"name": 'Dignity Health - Dominican Hospital', "city": 'Santa Cruz', "state": 'CA'},
            {"name": 'Dignity Health Chandler Regional Medical Center', "city": 'Chandler', "state": 'AZ'},
            {"name": 'CHI St. Vincent North', "city": 'Sherwood', "state": 'AR'},
            {"name": 'CHI Mercy Health', "city": 'Roseburg', "state": 'OR'},
            {"name": 'St. Joseph Medical Center', "city": 'Tacoma', "state": 'WA'},
            {"name": "Dignity Health - St. John's Regional Medical Center", "city": 'Oxnard', "state": 'CA'},
            {"name": 'St. Michael Medical Center', "city": 'Silverdale', "state": 'WA'},
            {"name": 'CHI Health Mercy Corning', "city": 'Corning', "state": 'IA'},
            {"name": 'Dignity Health – St. Elizabeth Community Hospital', "city": 'Red Bluff', "state": 'CA'},
            {"name": 'CHI Lisbon Health', "city": 'Lisbon', "state": 'ND'},
            {"name": 'CHI Franciscan Rehabilitation Hospital', "city": 'Tacoma', "state": 'WA'},
            {"name": 'CHI Health St. Elizabeth', "city": 'Lincoln', "state": 'NE'},
            {"name": 'Dignity Health - Mercy San Juan Medical Center', "city": 'Carmichael', "state": 'CA'},
            {"name": 'CHI Health Plainview', "city": 'Plainview', "state": 'NE'},
            {"name": 'CHI St. Vincent Infirmary', "city": 'Little Rock', "state": 'AR'},
            {"name": "CHI St. Gabriel's Hospital", "city": 'Little Falls', "state": 'MN'},
            {"name": 'Dignity Health - California Hospital Medical Center', "city": 'Los Angeles', "state": 'CA'},
            {"name": 'Dignity Health – Mercy Medical Center Mt. Shasta', "city": 'Mount Shasta', "state": 'CA'},
            {"name": 'CommonSpirit - Saint Joseph Medical Center - East Lexington', "city": 'Lexington', "state": 'KY'},
            {"name": "St. Luke's Health - Springwoods Village Hospital - Spring, TX", "city": 'Spring', "state": 'TX'},
            {"name": 'CommonSpirit Longmont United Hospital', "city": 'Longmont', "state": 'CO'},
            {"name": 'CommonSpirit - Saint Joseph Hospital - Bardstown', "city": 'Bardstown', "state": 'KY'},
            {"name": 'Dignity Health - Marian Regional Medical Center', "city": 'Santa Maria', "state": 'CA'},
            {"name": "Baylor St. Luke's Medical Center - Houston, TX", "city": 'Houston', "state": 'TX'},
            {"name": 'Dignity Health - Mercy Hospital of Folsom', "city": 'Folsom', "state": 'CA'},
            {"name": 'Dignity Health - Northridge Hospital Medical Center', "city": 'Northridge', "state": 'CA'},
            {"name": 'Dignity Health – Memorial Hospital', "city": 'Bakersfield', "state": 'CA'},
            {"name": "Baylor St. Luke's Medical Center - McNair Campus - Houston, TX", "city": 'Houston', "state": 'TX'},
            {"name": "St. Luke's Health - The Woodlands Hospital - The Woodlands, TX", "city": 'The Woodlands', "state": 'TX'},
            {"name": 'CommonSpirit - Saint Joseph Hospital - London', "city": 'London', "state": 'KY'},
            {"name": 'CommonSpirit St. Francis Hospital', "city": 'Colorado Springs', "state": 'CO'},
            {"name": 'CommonSpirit St. Elizabeth Hospital', "city": 'Fort Morgan', "state": 'CO'},
            {"name": 'CHI St. Alexius Health Garrison Memorial Hospital', "city": 'Garrison', "state": 'ND'},
            {"name": 'Dignity Health, Yavapai Regional Medical Center East', "city": 'Prescott Valley', "state": 'AZ'},
            {"name": 'Dignity Health - Mercy Hospital Southwest', "city": 'Bakersfield', "state": 'CA'},
            {"name": "St. Luke's Health - Patients Medical Center - Pasadena, TX", "city": 'Pasadena', "state": 'TX'},
            {"name": "CHI St. Joseph's Health", "city": 'Park Rapids', "state": 'MN'},
            {"name": 'Dignity Health - Arroyo Grande Community Hospital', "city": 'Arroyo Grande', "state": 'CA'},
            {"name": 'St. Anne Hospital', "city": 'Burien', "state": 'WA'},
            {"name": 'Dignity Health - Woodland Memorial Hospital', "city": 'Woodland', "state": 'CA'},
            {"name": 'Wellfound Behavioral Health Hospital', "city": 'Tacoma', "state": 'WA'},
            {"name": 'CommonSpirit Holy Cross Hospital - Salt Lake', "city": 'Salt Lake City', "state": 'UT'},
        ],
    },
    {
        "company": 'LifePoint Health',
        "source_url": 'https://www.lifepointhealth.net/locations',
        "verified_at": '2026-09-17',
        "hospitals": [
            {"name": 'Anderson Rehabilitation Institute', "city": 'Edwardsville', "state": 'IL'},
            {"name": 'Ascension Saint Thomas Rehabilitation Hospital', "city": 'Nashville', "state": 'TN'},
            {"name": 'Ashley Regional Medical Center', "city": 'Vernal', "state": 'UT'},
            {"name": 'Atlantic Rehabilitation Institute', "city": 'Madison', "state": 'NJ'},
            {"name": 'Baptist Health Rehabilitation Hospital', "city": 'South Miami', "state": 'FL'},
            {"name": 'Baptist Memorial Rehabilitation Hospital', "city": 'Germantown', "state": 'TN'},
            {"name": 'Baptist Memorial Rehabilitation Hospital-Madison', "city": 'Madison', "state": 'MS'},
            {"name": 'Beckett Springs', "city": 'West Chester Township', "state": 'OH'},
            {"name": 'Bolivar Medical Center', "city": 'Cleveland', "state": 'MS'},
            {"name": 'Canyon Vista Medical Center', "city": 'Sierra Vista', "state": 'AZ'},
            {"name": 'Carrollton Springs', "city": 'Carrollton', "state": 'TX'},
            {"name": 'Castleview Hospital', "city": 'Price', "state": 'UT'},
            {"name": 'Centerpoint Health - Georgetown', "city": 'Georgetown', "state": 'KY'},
            {"name": 'Centerpoint Health - Paris', "city": 'Paris', "state": 'KY'},
            {"name": 'Centerpoint Health - Versailles', "city": 'Versailles', "state": 'KY'},
            {"name": 'Centerpoint Health - Winchester', "city": 'Winchester', "state": 'KY'},
            {"name": 'Centra Behavioral Health Hospital', "city": 'Lynchburg', "state": 'VA'},
            {"name": 'Centra Rehabilitation Hospital', "city": 'Lynchburg', "state": 'VA'},
            {"name": 'Central Carolina Hospital', "city": 'Sanford', "state": 'NC'},
            {"name": 'Central Texas Rehabilitation Hospital', "city": 'Austin', "state": 'TX'},
            {"name": 'CHRISTUS Health Rehabilitation Hospital', "city": 'Longview', "state": 'TX'},
            {"name": 'Clinch Valley Health', "city": 'Richlands', "state": 'VA'},
            {"name": 'Collin Springs', "city": 'McKinney', "state": 'TX'},
            {"name": 'Columbus Springs Dublin', "city": 'Dublin', "state": 'OH'},
            {"name": 'Columbus Springs East', "city": 'Columbus', "state": 'OH'},
            {"name": 'Community Medical Center', "city": 'Missoula', "state": 'MT'},
            {"name": 'Community Rehabilitation Hospital North', "city": 'Indianapolis', "state": 'IN'},
            {"name": 'Community Rehabilitation Hospital South', "city": 'Greenwood', "state": 'IN'},
            {"name": 'Community Rehabilitation Hospital West', "city": 'Brownsburg', "state": 'IN'},
            {"name": 'Conemaugh Memorial Medical Center', "city": 'Johnstown', "state": 'PA'},
            {"name": 'Conemaugh Meyersdale Medical Center', "city": 'Meyersdale', "state": 'PA'},
            {"name": 'Conemaugh Miners Medical Center', "city": 'Hastings', "state": 'PA'},
            {"name": 'Conemaugh Nason Medical Center', "city": 'Roaring Spring', "state": 'PA'},
            {"name": 'Copper Springs', "city": 'Avondale', "state": 'AZ'},
            {"name": 'Copper Springs East', "city": 'Gilbert', "state": 'AZ'},
            {"name": 'Cottonwood Springs', "city": 'Olathe', "state": 'KS'},
            {"name": 'Denver Springs', "city": 'Englewood', "state": 'CO'},
            {"name": 'Dignity Health East Valley Rehabilitation Hospital', "city": 'Chandler', "state": 'AZ'},
            {"name": 'Dignity Health East Valley Rehabilitation Hospital – Gilbert', "city": 'Gilbert', "state": 'AZ'},
            {"name": 'Eastern Iowa Rehabilitation Hospital', "city": 'Coralville', "state": 'IA'},
            {"name": 'El Dorado Springs Behavioral Health', "city": 'Tucson', "state": 'AZ'},
            {"name": 'Ennis Regional Medical Center', "city": 'Ennis', "state": 'TX'},
            {"name": 'Fauquier Health', "city": 'Warrenton', "state": 'VA'},
            {"name": 'Fleming County Hospital', "city": 'Flemingsburg', "state": 'KY'},
            {"name": 'Frazier Rehabilitation Hospital - Brownsboro', "city": 'Louisville', "state": 'KY'},
            {"name": 'Frye Regional Medical Center', "city": 'Hickory', "state": 'NC'},
            {"name": 'Harris Regional Hospital', "city": 'Sylva', "state": 'NC'},
            {"name": 'Havasu Regional Medical Center', "city": 'Lake Havasu City', "state": 'AZ'},
            {"name": 'Haywood Regional Medical Center', "city": 'Clyde', "state": 'NC'},
            {"name": 'Highland Springs', "city": 'Highland Hills', "state": 'OH'},
            {"name": 'Highpoint Health – Riverview with Ascension Saint Thomas', "city": 'Carthage', "state": 'TN'},
            {"name": 'Highpoint Health – Sewanee with Ascension Saint Thomas', "city": 'Sewanee', "state": 'TN'},
            {"name": 'Highpoint Health – Sumner Station with Ascension Saint Thomas', "city": 'Gallatin', "state": 'TN'},
            {"name": 'Highpoint Health – Sumner with Ascension Saint Thomas', "city": 'Gallatin', "state": 'TN'},
            {"name": 'Highpoint Health – Trousdale with Ascension Saint Thomas', "city": 'Hartsville', "state": 'TN'},
            {"name": 'Highpoint Health – Winchester with Ascension Saint Thomas', "city": 'Winchester', "state": 'TN'},
            {"name": 'Hospital Sisters Health System | Rehabilitation Hospital', "city": 'Green Bay', "state": 'WI'},
            {"name": 'Jackson Purchase Medical Center', "city": 'Mayfield', "state": 'KY'},
            {"name": 'Jefferson Regional Specialty Hospital', "city": 'White Hall', "state": 'AR'},
            {"name": 'Jefferson Regional Specialty Hospital', "city": 'White Hall', "state": 'AR'},
            {"name": 'Knoxville Rehabilitation Hospital', "city": 'Knoxville', "state": 'TN'},
            {"name": 'Lake Cumberland Regional Hospital', "city": 'Somerset', "state": 'KY'},
            {"name": 'Lancaster Rehabilitation Hospital', "city": 'Lancaster', "state": 'PA'},
            {"name": 'Liberty Rehabilitation Hospital', "city": 'Liberty Township', "state": 'OH'},
            {"name": 'Livingston Regional Hospital', "city": 'Livingston', "state": 'TN'},
            {"name": 'Logan Regional Medical Center', "city": 'Logan', "state": 'WV'},
            {"name": 'Los Alamos Medical Center', "city": 'Los Alamos', "state": 'NM'},
            {"name": 'Lourdes Behavioral Health', "city": 'Richland', "state": 'WA'},
            {"name": 'Lourdes Health', "city": 'Pasco', "state": 'WA'},
            {"name": 'Maria Parham Franklin', "city": 'Louisburg', "state": 'NC'},
            {"name": 'Maria Parham Health', "city": 'Henderson', "state": 'NC'},
            {"name": 'Meadowview Regional Medical Center', "city": 'Maysville', "state": 'KY'},
            {"name": 'Memorial Medical Center', "city": 'Las Cruces', "state": 'NM'},
            {"name": 'Mercy Health Behavioral Hospital', "city": 'Youngstown', "state": 'OH'},
            {"name": 'Mercy Health Rehabilitation Hospital', "city": 'Youngstown', "state": 'OH'},
            {"name": 'Mercy Rehabilitation Hospital (Northwest Arkansas)', "city": 'Rogers', "state": 'AR'},
            {"name": 'Mercy Rehabilitation Hospital (Oklahoma City)', "city": 'Oklahoma City', "state": 'OK'},
            {"name": 'Mercy Rehabilitation Hospital (Springfield)', "city": 'Springfield', "state": 'MO'},
            {"name": 'Mercy Rehabilitation Hospital (St. Louis)', "city": 'Chesterfield', "state": 'MO'},
            {"name": 'Mercy Rehabilitation Hospital Oklahoma City South', "city": 'Oklahoma City', "state": 'OK'},
            {"name": 'Mercy Rehabilitation Hospital South', "city": 'St. Louis', "state": 'MO'},
            {"name": 'MercyOne Clive Rehabilitation Hospital', "city": 'Clive', "state": 'IA'},
            {"name": 'Mesa Springs', "city": 'Ft. Worth', "state": 'TX'},
            {"name": 'Methodist Rehabilitation Hospital', "city": 'Dallas', "state": 'TX'},
            {"name": 'National Park Medical Center', "city": 'Hot Springs', "state": 'AR'},
            {"name": 'North Alabama Medical Center', "city": 'Florence', "state": 'AL'},
            {"name": 'North Florida Rehabilitation Hospital', "city": 'Jacksonville', "state": 'FL'},
            {"name": 'Northeast Georgia Rehabilitation Institute', "city": 'Gainesville', "state": 'GA'},
            {"name": 'Northeastern Nevada Regional Hospital', "city": 'Elko', "state": 'NV'},
            {"name": 'Oakwood Springs', "city": 'Oklahoma City', "state": 'OK'},
            {"name": 'Ottumwa Regional Health Center', "city": 'Ottumwa', "state": 'IA'},
            {"name": 'Palestine Regional Medical Center', "city": 'Palestine', "state": 'TX'},
            {"name": 'Palomar Health Rehabilitation Institute', "city": 'Escondido', "state": 'CA'},
            {"name": 'Paris Regional Health', "city": 'Paris', "state": 'TX'},
            {"name": 'Parkview Regional Hospital', "city": 'Mexia', "state": 'TX'},
            {"name": 'PeaceHealth Springfield Rehabilitation Hospital (Opening September 2026)', "city": 'Springfield', "state": 'OR'},
            {"name": 'Peak Rehabilitation Hospital', "city": 'Apex', "state": 'NC'},
            {"name": 'Person Memorial Hospital', "city": 'Roxboro', "state": 'NC'},
            {"name": 'Providence Swedish Rehabilitation Hospital', "city": 'Lynnwood', "state": 'WA'},
            {"name": 'Raleigh General Hospital', "city": 'Beckley', "state": 'WV'},
            {"name": 'Rehabilitation Hospital of Oak Creek', "city": 'Oak Creek', "state": 'WI'},
            {"name": 'Rehabilitation Hospital of Rhode Island', "city": 'North Smithfield', "state": 'RI'},
            {"name": 'Rehabilitation Hospital of Wisconsin', "city": 'Waukesha', "state": 'WI'},
            {"name": 'Rehabilitation Institute of South San Antonio', "city": 'San Antonio', "state": 'TX'},
            {"name": 'Rock Springs', "city": 'Georgetown', "state": 'TX'},
            {"name": 'Rutherford Regional Health System', "city": 'Rutherfordton', "state": 'NC'},
            {"name": "Saint Mary's Regional Health System", "city": 'Russellville', "state": 'AR'},
            {"name": 'Saline Memorial Hospital', "city": 'Benton', "state": 'AR'},
            {"name": 'Shoals Hospital', "city": 'Muscle Shoals', "state": 'AL'},
            {"name": 'Sovah Health - Danville', "city": 'Danville', "state": 'VA'},
            {"name": 'Sovah Health - Martinsville', "city": 'Martinsville', "state": 'VA'},
            {"name": 'Spring View Hospital', "city": 'Lebanon', "state": 'KY'},
            {"name": 'St. Joseph Regional Medical Center', "city": 'Lewiston', "state": 'ID'},
            {"name": 'St. Mary Rehabilitation Hospital', "city": 'Langhorne', "state": 'PA'},
            {"name": 'Starr Regional Medical Center - Athens', "city": 'Athens', "state": 'TN'},
            {"name": 'Starr Regional Medical Center - Etowah', "city": 'Etowah', "state": 'TN'},
            {"name": 'STRHS Lawrenceburg', "city": 'Lawrenceburg', "state": 'TN'},
            {"name": 'STRHS Pulaski', "city": 'Pulaski', "state": 'TN'},
            {"name": 'Swain Community Hospital', "city": 'Bryson City', "state": 'NC'},
            {"name": 'Sycamore Springs', "city": 'Lafayette', "state": 'IN'},
            {"name": 'Temple Rehabilitation Hospital', "city": 'Temple', "state": 'TX'},
            {"name": 'Texas Rehabilitation Hospital of Arlington', "city": 'Arlington', "state": 'TX'},
            {"name": 'Texas Rehabilitation Hospital of Fort Worth', "city": 'Fort Worth', "state": 'TX'},
            {"name": 'Texas Rehabilitation Hospital of Keller', "city": 'Keller', "state": 'TX'},
            {"name": 'Texas Rehabilitation Hospital of Plano (Opening October 2026)', "city": 'Plano', "state": 'TX'},
            {"name": 'TGH Behavioral Health Hospital', "city": 'Tampa', "state": 'FL'},
            {"name": 'TGH Rehabilitation Hospital', "city": 'Tampa', "state": 'FL'},
            {"name": 'The Hospitals of Providence Rehabilitation Hospital East (formerly El Paso Rehabilitation Hospital)', "city": 'El Paso', "state": 'TX'},
            {"name": 'The Rehabilitation Hospital of Montana', "city": 'Billings', "state": 'MT'},
            {"name": 'Triangle Springs', "city": 'Raleigh', "state": 'NC'},
            {"name": 'Trios Health', "city": 'Kennewick', "state": 'WA'},
            {"name": 'Twin County Regional Healthcare', "city": 'Galax', "state": 'VA'},
            {"name": 'UC Davis Rehabilitation Hospital', "city": 'Sacramento', "state": 'CA'},
            {"name": 'UCI Health – Irvine Rehabilitation Hospital', "city": 'Irvine', "state": 'CA'},
            {"name": 'University Hospitals Avon Rehabilitation Hospital', "city": 'Avon', "state": 'OH'},
            {"name": 'University Hospitals Rehabilitation Hospital', "city": 'Beachwood', "state": 'OH'},
            {"name": 'UP Health System - Bell', "city": 'Ishpeming', "state": 'MI'},
            {"name": 'UP Health System - Marquette', "city": 'Marquette', "state": 'MI'},
            {"name": 'UP Health System - Portage', "city": 'Hancock', "state": 'MI'},
            {"name": 'UW Health Rehabilitation Hospital', "city": 'Madison', "state": 'WI'},
            {"name": 'Valley Springs Behavioral Health Hospital', "city": 'Holyoke', "state": 'MA'},
            {"name": 'Valley View Medical Center', "city": 'Fort Mohave', "state": 'AZ'},
            {"name": 'Virginia Mason Franciscan Health Rehabilitation Hospital', "city": 'Tacoma', "state": 'WA'},
            {"name": 'Watertown Regional Medical Center', "city": 'Watertown', "state": 'WI'},
            {"name": 'WellBridge Healthcare Fort Worth', "city": 'Fort Worth', "state": 'TX'},
            {"name": 'Westpark Springs', "city": 'Richmond', "state": 'TX'},
            {"name": 'Willamette Valley Medical Center', "city": 'McMinnville', "state": 'OR'},
            {"name": 'Wilson Medical Center', "city": 'Wilson', "state": 'NC'},
            {"name": 'Woodland Springs', "city": 'Conroe', "state": 'TX'},
            {"name": 'Wythe County Community Hospital', "city": 'Wytheville', "state": 'VA'},
            {"name": 'Mercy Rehabilitation Hospital (Fort Smith)', "city": 'Fort Smith', "state": 'AR'},
            {"name": 'Rainier Springs', "city": 'Vancouver', "state": 'WA'},
        ],
    },
    {
        "company": 'ScionHealth',
        "source_url": 'https://www.scionhealth.com/find-a-location',
        "verified_at": '2026-09-17',
        "hospitals": [
            {"name": 'Cornerstone Specialty Hospitals Broken Arrow', "city": 'Broken Arrow', "state": 'OK'},
            {"name": 'Cornerstone Specialty Hospitals Conroe', "city": 'Conroe', "state": 'TX'},
            {"name": 'Cornerstone Specialty Hospitals Huntington', "city": 'Huntington', "state": 'WV'},
            {"name": 'Cornerstone Specialty Hospitals Little Rock', "city": 'Little Rock', "state": 'AR'},
            {"name": 'Cornerstone Specialty Hospitals Muskogee', "city": 'Muskogee', "state": 'OK'},
            {"name": 'Cornerstone Specialty Hospitals Round Rock', "city": 'Round Rock', "state": 'TX'},
            {"name": 'Kindred Hospital Albuquerque', "city": 'Albuquerque', "state": 'NM'},
            {"name": 'Kindred Hospital Aurora', "city": 'Aurora', "state": 'CO'},
            {"name": 'Kindred Hospital Baldwin Park', "city": 'Baldwin Park', "state": 'CA'},
            {"name": 'Kindred Hospital Bay Area - St. Petersburg', "city": 'St. Petersburg', "state": 'FL'},
            {"name": 'Kindred Hospital Brea', "city": 'Brea', "state": 'CA'},
            {"name": 'Kindred Hospital Central Tampa', "city": 'Tampa', "state": 'FL'},
            {"name": 'Kindred Hospital Chattanooga', "city": 'Chattanooga', "state": 'TN'},
            {"name": 'Kindred Hospital Chicago - North', "city": 'Chicago', "state": 'IL'},
            {"name": 'Kindred Hospital Chicago - Northlake', "city": 'Northlake', "state": 'IL'},
            {"name": 'Kindred Hospital Clear Lake', "city": 'Webster', "state": 'TX'},
            {"name": 'Kindred Hospital Dallas Central', "city": 'Dallas', "state": 'TX'},
            {"name": 'Kindred Hospital Dayton', "city": 'Dayton', "state": 'OH'},
            {"name": 'Kindred Hospital Denver', "city": 'Denver', "state": 'CO'},
            {"name": 'Kindred Hospital East New Jersey', "city": 'Passaic', "state": 'NJ'},
            {"name": 'Kindred Hospital El Paso', "city": 'El Paso', "state": 'TX'},
            {"name": 'Kindred Hospital Greensboro', "city": 'Greensboro', "state": 'NC'},
            {"name": 'Kindred Hospital Houston Medical Center', "city": 'Houston', "state": 'TX'},
            {"name": 'Kindred Hospital Houston Northwest', "city": 'Houston', "state": 'TX'},
            {"name": 'Kindred Hospital Indianapolis', "city": 'Indianapolis', "state": 'IN'},
            {"name": 'Kindred Hospital Indianapolis North', "city": 'Indianapolis', "state": 'IN'},
            {"name": 'Kindred Hospital Las Vegas - Flamingo', "city": 'Las Vegas', "state": 'NV'},
            {"name": 'Kindred Hospital Las Vegas - Sahara', "city": 'Las Vegas', "state": 'NV'},
            {"name": 'Kindred Hospital Lima', "city": 'Lima', "state": 'OH'},
            {"name": 'Kindred Hospital Los Angeles', "city": 'Los Angeles', "state": 'CA'},
            {"name": 'Kindred Hospital Louisville', "city": 'Louisville', "state": 'KY'},
            {"name": 'Kindred Hospital Louisville at Jewish Hospital', "city": 'Louisville', "state": 'KY'},
            {"name": 'Kindred Hospital Melbourne', "city": 'Melbourne', "state": 'FL'},
            {"name": 'Kindred Hospital New Jersey - Morris County', "city": 'Dover', "state": 'NJ'},
            {"name": 'Kindred Hospital New Jersey - Rahway', "city": 'Rahway', "state": 'NJ'},
            {"name": 'Kindred Hospital North Florida', "city": 'Green Cove Springs', "state": 'FL'},
            {"name": 'Kindred Hospital Northland', "city": 'Kansas City', "state": 'MO'},
            {"name": 'Kindred Hospital Ontario', "city": 'Ontario', "state": 'CA'},
            {"name": 'Kindred Hospital Paramount', "city": 'Paramount', "state": 'CA'},
            {"name": 'Kindred Hospital Philadelphia', "city": 'Philadelphia', "state": 'PA'},
            {"name": 'Kindred Hospital Philadelphia - Havertown', "city": 'Havertown', "state": 'PA'},
            {"name": 'Kindred Hospital Rancho', "city": 'Rancho Cucamonga', "state": 'CA'},
            {"name": 'Kindred Hospital Riverside', "city": 'Perris', "state": 'CA'},
            {"name": 'Kindred Hospital San Antonio', "city": 'San Antonio', "state": 'TX'},
            {"name": 'Kindred Hospital San Antonio Central', "city": 'San Antonio', "state": 'TX'},
            {"name": 'Kindred Hospital San Diego', "city": 'San Diego', "state": 'CA'},
            {"name": 'Kindred Hospital San Francisco Bay Area', "city": 'San Leandro', "state": 'CA'},
            {"name": 'Kindred Hospital San Gabriel Valley', "city": 'West Covina', "state": 'CA'},
            {"name": 'Kindred Hospital Santa Ana', "city": 'Santa Ana', "state": 'CA'},
            {"name": 'Kindred Hospital Seattle - First Hill', "city": 'Seattle', "state": 'WA'},
            {"name": 'Kindred Hospital South Bay', "city": 'Gardena', "state": 'CA'},
            {"name": 'Kindred Hospital South Florida - Coral Gables', "city": 'Coral Gables', "state": 'FL'},
            {"name": 'Kindred Hospital South Florida - Ft. Lauderdale', "city": 'Ft. Lauderdale', "state": 'FL'},
            {"name": 'Kindred Hospital South Florida - Hollywood', "city": 'Hollywood', "state": 'FL'},
            {"name": 'Kindred Hospital St. Louis South', "city": 'St. Louis', "state": 'MO'},
            {"name": 'Kindred Hospital Sugar Land', "city": 'Sugar Land', "state": 'TX'},
            {"name": 'Kindred Hospital Tarrant County - Arlington', "city": 'Arlington', "state": 'TX'},
            {"name": 'Kindred Hospital Tarrant County - Fort Worth Southwest', "city": 'Fort Worth', "state": 'TX'},
            {"name": 'Kindred Hospital The Palm Beaches', "city": 'Riviera Beach', "state": 'FL'},
            {"name": 'Kindred Hospital Westminster', "city": 'Westminster', "state": 'CA'},
            {"name": 'Solara Specialty Hospitals Harlingen', "city": 'Harlingen', "state": 'TX'},
            {"name": 'Solara Specialty Hospitals McAllen', "city": 'McAllen', "state": 'TX'},
            {"name": 'Andalusia Health', "city": 'Andalusia', "state": 'AL'},
            {"name": 'Carolina Pines Regional Medical Center', "city": 'Hartsville', "state": 'SC'},
            {"name": 'SageWest Health Care - Lander', "city": 'Lander', "state": 'WY'},
            {"name": 'SageWest Health Care - Riverton', "city": 'Riverton', "state": 'WY'},
            {"name": 'St. Francis-Emory Healthcare', "city": 'Columbus', "state": 'GA'},
            {"name": 'Vaughan Regional Medical Center', "city": 'Selma', "state": 'AL'},
        ],
    },
    {
        "company": "Christus Health",
        "source_url": 'https://www.christushealth.org/locations',
        "verified_at": '2026-09-17',
        "hospitals": [
            {"name": 'CHRISTUS Health - West Beaumont', "city": 'Beaumont', "state": 'TX'},
            {"name": 'CHRISTUS Mother Frances Hospital - Sulphur Springs', "city": 'Sulphur Springs', "state": 'TX'},
            {"name": 'CHRISTUS Hospital - Orange', "city": 'Orange', "state": 'TX'},
            {"name": 'CHRISTUS Health | Palestine, TX', "city": 'Palestine', "state": 'TX'},
            {"name": 'CHRISTUS Good Shepherd Medical Center - Marshall', "city": 'Marshall', "state": 'TX'},
            {"name": 'CHRISTUS Ochsner Lake Area Hospital', "city": 'Lake Charles', "state": 'LA'},
            {"name": 'CHRISTUS Ochsner St. Patrick Hospital', "city": 'Lake Charles', "state": 'LA'},
            {"name": "CHRISTUS Children's Hospital", "city": 'San Antonio', "state": 'TX'},
            {"name": 'CHRISTUS Health Pine Street', "city": 'Texarkana', "state": 'TX'},
            {"name": 'CHRISTUS Health (Alamogordo)', "city": 'Alamogordo', "state": 'NM'},
            {"name": 'CHRISTUS Mother Frances Hospital - Tyler', "city": 'Tyler', "state": 'TX'},
            {"name": 'CHRISTUS Mother Frances Hospital - Jacksonville', "city": 'Jacksonville', "state": 'TX'},
            {"name": 'CHRISTUS Santa Rosa Hospital - San Marcos', "city": 'San Marcos', "state": 'TX'},
            {"name": 'CHRISTUS Santa Rosa Hospital - Alamo Heights', "city": 'San Antonio', "state": 'TX'},
            {"name": 'CHRISTUS Mother Frances Hospital - South Tyler', "city": 'Tyler', "state": 'TX'},
            {"name": 'CHRISTUS Spohn Hospital - Kleberg', "city": 'Kingsville', "state": 'TX'},
            {"name": 'CHRISTUS Spohn Hospital Corpus Christi - South', "city": 'Corpus Christi', "state": 'TX'},
            {"name": 'CHRISTUS Spohn Hospital Corpus Christi - Shoreline', "city": 'Corpus Christi', "state": 'TX'},
            {"name": 'CHRISTUS Spohn Hospital - Beeville', "city": 'Beeville', "state": 'TX'},
            {"name": 'CHRISTUS Southeast Texas - Jasper Memorial', "city": 'Jasper', "state": 'TX'},
            {"name": 'CHRISTUS Trinity Mother Frances Hospital - Winnsboro', "city": 'Winnsboro', "state": 'TX'},
            {"name": 'CHRISTUS St. Frances Cabrini', "city": 'Alexandria', "state": 'LA'},
            {"name": 'CHRISTUS Coushatta Health Care Center', "city": 'Coushatta', "state": 'LA'},
            {"name": 'CHRISTUS St. Michael Hospital - Atlanta', "city": 'Atlanta', "state": 'TX'},
            {"name": 'CHRISTUS Health (Mount Pleasant)', "city": 'Mount Pleasant', "state": 'TX'},
            {"name": 'CHRISTUS Southeast Texas - St. Elizabeth', "city": 'Beaumont', "state": 'TX'},
            {"name": 'CHRISTUS Spohn Hospital - Alice', "city": 'Alice', "state": 'TX'},
            {"name": 'CHRISTUS St. Vincent Regional Medical Center', "city": 'Santa Fe', "state": 'NM'},
            {"name": 'CHRISTUS Highland Medical Center', "city": 'Shreveport', "state": 'LA'},
            {"name": 'CHRISTUS St. Michael Hospital', "city": 'Texarkana', "state": 'TX'},
            {"name": 'CHRISTUS Santa Rosa Hospital - Westover Hills', "city": 'San Antonio', "state": 'TX'},
            {"name": 'CHRISTUS Santa Rosa Hospital - New Braunfels', "city": 'New Braunfels', "state": 'TX'},
        ],
    },
    {
        "company": 'Community Health Systems',
        "source_url": 'https://www.chs.net/serving-communities/locations',
        "verified_at": '2026-09-17',
        "hospitals": [
            {"name": 'Baldwin Health', "city": 'Foley', "state": 'AL'},
            {"name": 'Flowers Hospital', "city": 'Dothan', "state": 'AL'},
            {"name": 'Gadsden Regional Medical Center', "city": 'Gadsden', "state": 'AL'},
            {"name": 'Grandview Medical Center', "city": 'Birmingham', "state": 'AL'},
            {"name": 'Medical Center Enterprise', "city": 'Enterprise', "state": 'AL'},
            {"name": 'Mat-Su Regional Medical Center', "city": 'Palmer', "state": 'AK'},
            {"name": 'Northwest Medical Center', "city": 'Tucson', "state": 'AZ'},
            {"name": 'Northwest Medical Center - Sahuarita', "city": 'Sahuarita', "state": 'AZ'},
            {"name": 'Northwest Medical Center - Houghton', "city": 'Tucson', "state": 'AZ'},
            {"name": 'Northwest Transitions Inpatient Rehabilitation', "city": 'Tucson', "state": 'AZ'},
            {"name": "Northwest Women's Center", "city": 'Tucson', "state": 'AZ'},
            {"name": 'Oro Valley Hospital', "city": 'Tucson', "state": 'AZ'},
            {"name": 'Western Arizona Regional Medical Center', "city": 'Bullhead City', "state": 'AZ'},
            {"name": 'Depoo Medical Building', "city": 'Key West', "state": 'FL'},
            {"name": 'Lower Keys Medical Center', "city": 'Key West', "state": 'FL'},
            {"name": 'North Okaloosa Medical Center', "city": 'Crestview', "state": 'FL'},
            {"name": 'Physicians Regional Healthcare System - Collier ', "city": 'Naples', "state": 'FL'},
            {"name": 'Physicians Regional Healthcare System - Pine Ridge', "city": 'Naples', "state": 'FL'},
            {"name": 'Physicians Regional Healthcare System - North', "city": 'Naples', "state": 'FL'},
            {"name": 'Santa Rosa Medical Center', "city": 'Milton', "state": 'FL'},
            {"name": 'East Georgia Regional Medical Center', "city": 'Statesboro', "state": 'GA'},
            {"name": 'Bluffton Regional Medical Center', "city": 'Bluffton', "state": 'IN'},
            {"name": 'Dukes Memorial Hospital', "city": 'Peru', "state": 'IN'},
            {"name": 'Dupont Hospital', "city": 'Fort Wayne', "state": 'IN'},
            {"name": 'Lutheran Kosciusko Hospital', "city": 'Warsaw', "state": 'IN'},
            {"name": 'Northwest Health - La Porte', "city": 'La Porte', "state": 'IN'},
            {"name": 'Lutheran Hospital', "city": 'Fort Wayne', "state": 'IN'},
            {"name": 'Lutheran Downtown Hospital', "city": 'Fort Wayne', "state": 'IN'},
            {"name": 'Northwest Health - Portage', "city": 'Portage', "state": 'IN'},
            {"name": 'Northwest Health - Porter', "city": 'Valparaiso', "state": 'IN'},
            {"name": 'Northwest Health - Starke', "city": 'Knox', "state": 'IN'},
            {"name": 'The Orthopedic Hospital', "city": 'Fort Wayne', "state": 'IN'},
            {"name": 'Merit Health Central', "city": 'Jackson', "state": 'MS'},
            {"name": 'Merit Health Natchez', "city": 'Natchez', "state": 'MS'},
            {"name": 'Merit Health Rankin', "city": 'Brandon', "state": 'MS'},
            {"name": 'Merit Health River Oaks', "city": 'Flowood', "state": 'MS'},
            {"name": 'Merit Health River Region', "city": 'Vicksburg', "state": 'MS'},
            {"name": 'Merit Health Wesley', "city": 'Hattiesburg', "state": 'MS'},
            {"name": "Merit Health Woman's Hospital", "city": 'Flowood', "state": 'MS'},
            {"name": 'Moberly Regional Medical Center', "city": 'Moberly', "state": 'MO'},
            {"name": 'Northeast Regional Medical Center', "city": 'Kirksville', "state": 'MO'},
            {"name": 'Poplar Bluff Regional Medical Center', "city": 'Poplar Bluff', "state": 'MO'},
            {"name": 'Poplar Bluff Regional Medical Center - Westwood', "city": 'Poplar Bluff', "state": 'MO'},
            {"name": 'Carlsbad Medical Center', "city": 'Carlsbad', "state": 'NM'},
            {"name": 'Eastern New Mexico Medical Center', "city": 'Roswell', "state": 'NM'},
            {"name": 'MountainView Regional Medical Center', "city": 'Las Cruces', "state": 'NM'},
            {"name": 'AllianceHealth Durant', "city": 'Durant', "state": 'OK'},
            {"name": 'AllianceHealth Madill', "city": 'Madill', "state": 'OK'},
            {"name": 'Tennova - Jefferson Memorial Hospital', "city": 'Jefferson City', "state": 'TN'},
            {"name": 'Tennova - LaFollette Medical Center', "city": 'LaFollette', "state": 'TN'},
            {"name": 'Tennova - Newport Medical Center', "city": 'Newport', "state": 'TN'},
            {"name": 'Tennova - North Knoxville Medical Center', "city": 'Powell', "state": 'TN'},
            {"name": 'Tennova - Turkey Creek Medical Center', "city": 'Knoxville', "state": 'TN'},
            {"name": 'DeTar Healthcare System', "city": 'Victoria', "state": 'TX'},
            {"name": 'DeTar Healthcare System - North', "city": 'Victoria', "state": 'TX'},
            {"name": 'Lake Granbury Medical Center', "city": 'Granbury', "state": 'TX'},
            {"name": 'Laredo Medical Center', "city": 'Laredo', "state": 'TX'},
            {"name": 'Longview Regional Medical Center', "city": 'Longview', "state": 'TX'},
            {"name": 'Navarro Regional Hospital', "city": 'Corsicana', "state": 'TX'},
            {"name": 'Woodland Heights Medical Center', "city": 'Lufkin', "state": 'TX'},
        ],
    },
    {
        "company": 'Tenet Healthcare',
        "source_url": 'https://www.tenethealth.com/locations',
        "verified_at": '2026-09-17',
        "hospitals": [
            {"name": 'Abrazo Arizona Heart Hospital', "city": 'Phoenix', "state": 'AZ'},
            {"name": 'Abrazo Arrowhead Campus', "city": 'Glendale', "state": 'AZ'},
            {"name": 'Abrazo Central Campus', "city": 'Phoenix', "state": 'AZ'},
            {"name": 'Abrazo Scottsdale Campus', "city": 'Phoenix', "state": 'AZ'},
            {"name": 'Abrazo West Campus', "city": 'Goodyear', "state": 'AZ'},
            {"name": 'Baptist Medical Center', "city": 'San Antonio', "state": 'TX'},
            {"name": "Children's Hospital of Michigan - Main Campus", "city": 'Detroit', "state": 'MI'},
            {"name": 'Delray Medical Center', "city": 'Delray Beach', "state": 'FL'},
            {"name": 'Desert Regional Medical Center', "city": 'Palm Springs', "state": 'CA'},
            {"name": 'DMC Detroit Receiving Hospital', "city": 'Detroit', "state": 'MI'},
            {"name": 'DMC Harper University Hospital', "city": 'Detroit', "state": 'MI'},
            {"name": 'DMC Huron Valley-Sinai Hospital', "city": 'Commerce Charter Twp', "state": 'MI'},
            {"name": "DMC Hutzel Women's Hospital", "city": 'Detroit', "state": 'MI'},
            {"name": 'DMC Rehabilitation Institute of Michigan', "city": 'Detroit', "state": 'MI'},
            {"name": 'DMC Sinai-Grace Hospital', "city": 'Detroit', "state": 'MI'},
            {"name": 'Doctors Hospital of Manteca', "city": 'Manteca', "state": 'CA'},
            {"name": 'Doctors Medical Center Modesto', "city": 'Modesto', "state": 'CA'},
            {"name": 'Emanuel Medical Center', "city": 'Turlock', "state": 'CA'},
            {"name": 'Florida Coast Medical Center', "city": 'Port St. Lucie', "state": 'FL'},
            {"name": 'Framingham Union Hospital', "city": 'Framingham', "state": 'MA'},
            {"name": 'Good Samaritan Medical Center', "city": 'West Palm Beach', "state": 'FL'},
            {"name": 'Hi-Desert Medical Center', "city": 'Joshua Tree', "state": 'CA'},
            {"name": 'Holy Cross Hospital', "city": 'Nogales', "state": 'AZ'},
            {"name": 'JFK Memorial Hospital', "city": 'Indio', "state": 'CA'},
            {"name": 'Leonard Morse Hospital', "city": 'Natick', "state": 'MA'},
            {"name": 'Mission Trail Baptist Hospital', "city": 'San Antonio', "state": 'TX'},
            {"name": 'Nacogdoches Medical Center', "city": 'Nacogdoches', "state": 'TX'},
            {"name": 'North Central Baptist Hospital', "city": 'San Antonio', "state": 'TX'},
            {"name": 'Northeast Baptist Hospital', "city": 'San Antonio', "state": 'TX'},
            {"name": 'Palm Beach Children’s Hospital', "city": 'West Palm Beach', "state": 'FL'},
            {"name": 'Palm Beach Gardens Medical Center', "city": 'Palm Beach Gardens', "state": 'FL'},
            {"name": 'Piedmont Medical Center', "city": 'Rock Hill', "state": 'SC'},
            {"name": 'Piedmont Medical Center - Fort Mill', "city": 'Fort Mill', "state": 'SC'},
            {"name": 'Resolute Baptist Hospital', "city": 'New Braunfels', "state": 'TX'},
            {"name": 'Saint Francis Hospital - Memphis', "city": 'Memphis', "state": 'TN'},
            {"name": 'Saint Francis Hospital-Bartlett', "city": 'Bartlett', "state": 'TN'},
            {"name": 'Saint Vincent Hospital', "city": 'Worcester', "state": 'MA'},
            {"name": 'San Ramon Regional Medical Center', "city": 'San Ramon', "state": 'CA'},
            {"name": "St. Joseph's Hospital", "city": 'Tucson', "state": 'AZ'},
            {"name": "St. Luke's Baptist Hospital", "city": 'San Antonio', "state": 'TX'},
            {"name": "St. Mary's Hospital", "city": 'Tucson', "state": 'AZ'},
            {"name": "St. Mary's Medical Center", "city": 'West Palm Beach', "state": 'FL'},
            {"name": 'The Hospitals of Providence - East Campus', "city": 'El Paso', "state": 'TX'},
            {"name": 'The Hospitals of Providence - Memorial Campus', "city": 'El Paso', "state": 'TX'},
            {"name": 'The Hospitals of Providence - Sierra Campus', "city": 'El Paso', "state": 'TX'},
            {"name": 'The Hospitals of Providence - Transmountain Campus', "city": 'El Paso', "state": 'TX'},
            {"name": 'Valley Baptist Medical Center – Brownsville', "city": 'Brownsville', "state": 'TX'},
            {"name": 'Valley Baptist Medical Center – Harlingen', "city": 'Harlingen', "state": 'TX'},
            {"name": 'West Boca Medical Center', "city": 'Boca Raton', "state": 'FL'},
            {"name": 'Westover Hills Baptist Hospital', "city": 'San Antonio', "state": 'TX'},
        ],
    },
    {
        "company": 'Sanford Health',
        "source_url": 'https://www.sanfordhealth.org/locations',
        "verified_at": '2026-09-17',
        "hospitals": [
            {"name": 'Marshfield Medical Center - Beaver Dam', "city": 'Beaver Dam', "state": 'WI'},
            {"name": 'Community Memorial Hospital', "city": 'Burke', "state": 'SD'},
            {"name": 'Marshfield Medical Center - Dickinson', "city": 'Iron Mountain', "state": 'MI'},
            {"name": 'Marshfield Medical Center - Eau Claire', "city": 'Eau Claire', "state": 'WI'},
            {"name": 'Marshfield Medical Center - Ladysmith', "city": 'Ladysmith', "state": 'WI'},
            {"name": "Marshfield Children's Hospital", "city": 'Marshfield', "state": 'WI'},
            {"name": 'Marshfield Medical Center - Marshfield', "city": 'Marshfield', "state": 'WI'},
            {"name": 'Marshfield Medical Center - Minocqua', "city": 'Minocqua', "state": 'WI'},
            {"name": 'Marshfield Medical Center - Neillsville', "city": 'Neillsville', "state": 'WI'},
            {"name": 'Marshfield Medical Center - Park Falls', "city": 'Park Falls', "state": 'WI'},
            {"name": 'Marshfield Medical Center - Rice Lake', "city": 'Rice Lake', "state": 'WI'},
            {"name": 'Sanford Aberdeen Medical Center', "city": 'Aberdeen', "state": 'SD'},
            {"name": 'Sanford Bagley Medical Center', "city": 'Bagley', "state": 'MN'},
            {"name": 'Sanford Bemidji Medical Center', "city": 'Bemidji', "state": 'MN'},
            {"name": 'Sanford Bismarck Medical Center', "city": 'Bismarck', "state": 'ND'},
            {"name": 'Sanford Broadway Medical Center', "city": 'Fargo', "state": 'ND'},
            {"name": 'Sanford Canby Medical Center', "city": 'Canby', "state": 'MN'},
            {"name": 'Sanford Canton-Inwood Medical Center', "city": 'Canton', "state": 'SD'},
            {"name": 'Sanford Chamberlain Medical Center', "city": 'Chamberlain', "state": 'SD'},
            {"name": "Sanford Children's Hospital Bismarck", "city": 'Bismarck', "state": 'ND'},
            {"name": "Sanford Children's Hospital Fargo", "city": 'Fargo', "state": 'ND'},
            {"name": "Sanford Children's Hospital Sioux Falls", "city": 'Sioux Falls', "state": 'SD'},
            {"name": 'Sanford Heart Hospital', "city": 'Sioux Falls', "state": 'SD'},
            {"name": 'Sanford Hillsboro Medical Center', "city": 'Hillsboro', "state": 'ND'},
            {"name": 'Sanford Jackson Medical Center', "city": 'Jackson', "state": 'MN'},
            {"name": 'Sanford Luverne Medical Center', "city": 'Luverne', "state": 'MN'},
            {"name": 'Sanford Mayville Medical Center', "city": 'Mayville', "state": 'ND'},
            {"name": 'Sanford Medical Center Fargo', "city": 'Fargo', "state": 'ND'},
            {"name": 'Sanford Orthopedic Hospital', "city": 'Sioux Falls', "state": 'SD'},
            {"name": 'Sanford Outpatient Cardiac Rehabilitation', "city": 'Sioux Falls', "state": 'SD'},
            {"name": 'Sanford Sheldon Medical Center', "city": 'Sheldon', "state": 'IA'},
            {"name": 'Sanford South University Medical Center', "city": 'Fargo', "state": 'ND'},
            {"name": 'Sanford Thief River Falls Behavioral Health Center', "city": 'Thief River Falls', "state": 'MN'},
            {"name": 'Sanford Thief River Falls Medical Center', "city": 'Thief River Falls', "state": 'MN'},
            {"name": 'Sanford Tracy Medical Center', "city": 'Tracy', "state": 'MN'},
            {"name": 'Sanford USD Medical Center', "city": 'Sioux Falls', "state": 'SD'},
            {"name": 'Sanford Vermillion Medical Center', "city": 'Vermillion', "state": 'SD'},
            {"name": 'Sanford Webster Medical Center', "city": 'Webster', "state": 'SD'},
            {"name": 'Sanford Westbrook Medical Center', "city": 'Westbrook', "state": 'MN'},
            {"name": 'Sanford Wheaton Medical Center', "city": 'Wheaton', "state": 'MN'},
            {"name": 'Sanford Worthington Medical Center', "city": 'Worthington', "state": 'MN'},
            {"name": 'Marshfield Medical Center - Stevens Point', "city": 'Stevens Point', "state": 'WI'},
            {"name": 'Marshfield Medical Center - Weston', "city": 'Weston', "state": 'WI'},
            {"name": 'Winner Regional Hospital', "city": 'Winner', "state": 'SD'},
            {"name": 'Marshfield Medical Center - Wisconsin Rapids', "city": 'Wisconsin Rapids', "state": 'WI'},
        ],
    },
    {
        "company": 'Baylor Scott & White Health',
        "source_url": 'https://www.bswhealth.com/locations/hospital',
        "verified_at": '2026-09-17',
        "hospitals": [
            {"name": 'Baylor Scott & White The Heart Hospital - Dallas', "city": 'Dallas', "state": 'TX'},
            {"name": 'Baylor Scott & White Charles A. Sammons Cancer Center - Dallas', "city": 'Dallas', "state": 'TX'},
            {"name": 'Baylor University Medical Center', "city": 'Dallas', "state": 'TX'},
            {"name": 'Baylor Scott & White T. Boone Pickens Cancer Hospital', "city": 'Dallas', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Uptown', "city": 'Dallas', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Irving', "city": 'Irving', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Sunnyvale', "city": 'Sunnyvale', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Plano', "city": 'Plano', "state": 'TX'},
            {"name": 'Baylor Scott & White The Heart Hospital - Plano', "city": 'Plano', "state": 'TX'},
            {"name": 'Baylor Scott & White Emergency Hospital - Grand Prairie', "city": 'Grand Prairie', "state": 'TX'},
            {"name": 'Baylor Scott & White Emergency Hospital - Murphy', "city": 'Murphy', "state": 'TX'},
            {"name": 'Baylor Scott & White Emergency Center - Forney', "city": 'Forney', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Lake Pointe', "city": 'Rowlett', "state": 'TX'},
            {"name": 'Baylor Scott & White Orthopedic and Spine Hospital - Arlington', "city": 'Arlington', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Grapevine', "city": 'Grapevine', "state": 'TX'},
            {"name": 'Baylor Scott & White Emergency Center - Wylie', "city": 'Wylie', "state": 'TX'},
            {"name": 'Baylor Scott & White Emergency Hospital - Rockwall', "city": 'Rockwall', "state": 'TX'},
            {"name": 'Baylor Scott & White Emergency Hospital - Colleyville', "city": 'Colleyville', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Frisco', "city": 'Frisco', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Centennial', "city": 'Frisco', "state": 'TX'},
            {"name": 'Baylor Scott & White Emergency Hospital - Mansfield', "city": 'Mansfield', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Waxahachie', "city": 'Waxahachie', "state": 'TX'},
            {"name": 'Baylor Scott & White The Heart Hospital - Waxahachie', "city": 'Waxahachie', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Trophy Club', "city": 'Trophy Club', "state": 'TX'},
            {"name": 'Baylor Scott & White Emergency Hospital - Keller', "city": 'Keller', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Frisco at PGA Parkway', "city": 'Frisco', "state": 'TX'},
            {"name": 'Baylor Scott & White Emergency Hospital - Aubrey', "city": 'Aubrey', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - McKinney', "city": 'McKinney', "state": 'TX'},
            {"name": 'Baylor Scott & White The Heart Hospital - McKinney', "city": 'McKinney', "state": 'TX'},
            {"name": 'Baylor Scott & White The Heart Hospital - Fort Worth', "city": 'Fort Worth', "state": 'TX'},
            {"name": "Andrews Women's Hospital at Baylor Scott & White - Fort Worth", "city": 'Fort Worth', "state": 'TX'},
            {"name": 'Baylor Scott & White All Saints Medical Center - Fort Worth', "city": 'Fort Worth', "state": 'TX'},
            {"name": 'Baylor Scott & White The Heart Hospital - Denton', "city": 'Denton', "state": 'TX'},
            {"name": 'Baylor Scott & White Emergency Hospital - Burleson', "city": 'Burleson', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Hillcrest', "city": 'Waco', "state": 'TX'},
            {"name": 'Baylor Scott & White Texas Spine & Joint Hospital', "city": 'Tyler', "state": 'TX'},
            {"name": 'Baylor Scott & White Continuing Care Hospital - Temple', "city": 'Temple', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Temple', "city": 'Temple', "state": 'TX'},
            {"name": "Baylor Scott & White McLane Children's Medical Center - Temple", "city": 'Temple', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - College Station', "city": 'College Station', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Taylor', "city": 'Taylor', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Round Rock', "city": 'Round Rock', "state": 'TX'},
            {"name": 'Baylor Scott & White Emergency Medical Center - Cedar Park', "city": 'Cedar Park', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Pflugerville', "city": 'Pflugerville', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Marble Falls', "city": 'Marble Falls', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Lakeway', "city": 'Lakeway', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Brenham', "city": 'Brenham', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Austin', "city": 'Austin', "state": 'TX'},
            {"name": 'Baylor Scott & White Medical Center - Buda', "city": 'Buda', "state": 'TX'},
        ],
    },
    {
        "company": 'AdventHealth',
        "source_url": 'https://www.adventhealth.com/locations',
        "verified_at": '2026-09-17',
        "hospitals": [
            {"name": 'AdventHealth Altamonte Springs', "city": 'Altamonte Springs', "state": 'FL'},
            {"name": 'AdventHealth Apopka', "city": 'Apopka', "state": 'FL'},
            {"name": 'AdventHealth Avista', "city": 'Louisville', "state": 'CO'},
            {"name": 'AdventHealth Carrollwood', "city": 'Tampa', "state": 'FL'},
            {"name": 'AdventHealth Castle Rock', "city": 'Castle Rock', "state": 'CO'},
            {"name": 'AdventHealth Celebration', "city": 'Celebration', "state": 'FL'},
            {"name": 'AdventHealth Central Texas', "city": 'Killeen', "state": 'TX'},
            {"name": 'AdventHealth Connerton', "city": "Land O' Lakes", "state": 'FL'},
            {"name": 'AdventHealth Dade City', "city": 'Dade City', "state": 'FL'},
            {"name": 'AdventHealth Daytona Beach', "city": 'Daytona Beach', "state": 'FL'},
            {"name": 'AdventHealth DeLand', "city": 'DeLand', "state": 'FL'},
            {"name": 'AdventHealth Durand', "city": 'Durand', "state": 'WI'},
            {"name": 'AdventHealth East Orlando', "city": 'Orlando', "state": 'FL'},
            {"name": 'AdventHealth Fish Memorial', "city": 'Orange City', "state": 'FL'},
            {"name": 'AdventHealth Gordon', "city": 'Calhoun', "state": 'GA'},
            {"name": 'AdventHealth Heart of Florida', "city": 'Davenport', "state": 'FL'},
            {"name": 'AdventHealth Hendersonville', "city": 'Hendersonville', "state": 'NC'},
            {"name": 'AdventHealth Kissimmee', "city": 'Kissimmee', "state": 'FL'},
            {"name": 'AdventHealth Lake Nona', "city": 'Orlando', "state": 'FL'},
            {"name": 'AdventHealth Lake Placid', "city": 'Lake Placid', "state": 'FL'},
            {"name": 'AdventHealth Lake Wales', "city": 'Lake Wales', "state": 'FL'},
            {"name": 'AdventHealth Lenexa City Center', "city": 'Lenexa', "state": 'KS'},
            {"name": 'AdventHealth Littleton', "city": 'Littleton', "state": 'CO'},
            {"name": 'AdventHealth Manchester', "city": 'Manchester', "state": 'KY'},
            {"name": 'AdventHealth Minneola', "city": 'Minneola', "state": 'FL'},
            {"name": 'AdventHealth Murray', "city": 'Chatsworth', "state": 'GA'},
            {"name": 'AdventHealth New Smyrna Beach', "city": 'New Smyrna Beach', "state": 'FL'},
            {"name": 'AdventHealth North Pinellas', "city": 'Tarpon Springs', "state": 'FL'},
            {"name": 'AdventHealth Ocala', "city": 'Ocala', "state": 'FL'},
            {"name": 'AdventHealth Orlando', "city": 'Orlando', "state": 'FL'},
            {"name": 'AdventHealth Ottawa', "city": 'Ottawa', "state": 'KS'},
            {"name": 'AdventHealth Palm Coast', "city": 'Palm Coast', "state": 'FL'},
            {"name": 'AdventHealth Palm Coast Parkway', "city": 'Palm Coast', "state": 'FL'},
            {"name": 'AdventHealth Parker', "city": 'Parker', "state": 'CO'},
            {"name": 'AdventHealth Polk', "city": 'Columbus', "state": 'NC'},
            {"name": 'AdventHealth Port Charlotte', "city": 'Port Charlotte', "state": 'FL'},
            {"name": 'AdventHealth Porter', "city": 'Denver', "state": 'CO'},
            {"name": 'AdventHealth Prairie Star', "city": 'Lenexa', "state": 'KS'},
            {"name": 'AdventHealth Redmond', "city": 'Rome', "state": 'GA'},
            {"name": 'AdventHealth Riverview', "city": 'Riverview', "state": 'FL'},
            {"name": 'AdventHealth Rollins Brook', "city": 'Lampasas', "state": 'TX'},
            {"name": 'AdventHealth Sebring', "city": 'Sebring', "state": 'FL'},
            {"name": 'AdventHealth Shawnee Mission', "city": 'Merriam', "state": 'KS'},
            {"name": 'AdventHealth South Overland Park', "city": 'Overland Park', "state": 'KS'},
            {"name": 'AdventHealth Tampa', "city": 'Tampa', "state": 'FL'},
            {"name": 'AdventHealth Waterman', "city": 'Tavares', "state": 'FL'},
            {"name": 'AdventHealth Wauchula', "city": 'Wauchula', "state": 'FL'},
            {"name": 'AdventHealth Wesley Chapel', "city": 'Wesley Chapel', "state": 'FL'},
            {"name": 'AdventHealth Winter Garden', "city": 'Winter Garden', "state": 'FL'},
            {"name": 'AdventHealth Winter Park', "city": 'Winter Park', "state": 'FL'},
            {"name": 'AdventHealth Zephyrhills', "city": 'Zephyrhills', "state": 'FL'},
            {"name": 'Texas Health Hospital Mansfield', "city": 'Mansfield', "state": 'TX'},
            {"name": 'Texas Health Huguley Hospital Fort Worth South', "city": 'Burleson', "state": 'TX'},
            {"name": 'UChicago Medicine AdventHealth Bolingbrook', "city": 'Bolingbrook', "state": 'IL'},
            {"name": 'UChicago Medicine AdventHealth GlenOaks', "city": 'Glendale Heights', "state": 'IL'},
            {"name": 'UChicago Medicine AdventHealth Hinsdale', "city": 'Hinsdale', "state": 'IL'},
            {"name": 'UChicago Medicine AdventHealth La Grange', "city": 'La Grange', "state": 'IL'},
        ],
    },
    {
        "company": 'Providence',
        "source_url": 'https://www.providence.org/locations',
        "verified_at": '2026-09-17',
        "hospitals": [
            {"name": 'Swedish First Hill Campus', "city": 'Seattle', "state": 'WA'},
            {"name": 'Swedish Cherry Hill Campus', "city": 'Seattle', "state": 'WA'},
            {"name": 'Swedish Ballard Campus', "city": 'Seattle', "state": 'WA'},
            {"name": 'Swedish Redmond Campus', "city": 'Redmond', "state": 'WA'},
            {"name": 'Swedish Edmonds Campus', "city": 'Edmonds', "state": 'WA'},
            {"name": 'Swedish Issaquah Campus', "city": 'Issaquah', "state": 'WA'},
            {"name": 'Swedish Mill Creek Campus', "city": 'Everett', "state": 'WA'},
            {"name": 'Providence Regional Medical Center Everett', "city": 'Everett', "state": 'WA'},
            {"name": 'Providence St. Peter Hospital', "city": 'Olympia', "state": 'WA'},
            {"name": 'Providence Centralia Hospital', "city": 'Centralia', "state": 'WA'},
            {"name": 'Providence Seaside Hospital', "city": 'Seaside', "state": 'OR'},
            {"name": 'Providence Hood River Memorial Hospital', "city": 'Hood River', "state": 'OR'},
            {"name": 'Providence Portland Medical Center', "city": 'Portland', "state": 'OR'},
            {"name": 'Providence St. Vincent Medical Center', "city": 'Portland', "state": 'OR'},
            {"name": 'Providence Milwaukie Hospital', "city": 'Milwaukie', "state": 'OR'},
            {"name": 'Providence Willamette Falls Medical Center', "city": 'Oregon City', "state": 'OR'},
            {"name": 'Providence Newberg Medical Center', "city": 'Newberg', "state": 'OR'},
            {"name": 'Kadlec Regional Medical Center', "city": 'Richland', "state": 'WA'},
            {"name": 'Providence Mount Carmel Hospital', "city": 'Colville', "state": 'WA'},
            {"name": 'Providence St. Mary Medical Center', "city": 'Apple Valley', "state": 'CA'},
            {"name": "Providence St. Joseph's Hospital", "city": 'Chewelah', "state": 'WA'},
            {"name": 'Providence Sacred Heart Medical Center', "city": 'Spokane', "state": 'WA'},
            {"name": "Sacred Heart Children's Hospital", "city": 'Spokane', "state": 'WA'},
            {"name": 'Providence Holy Family Hospital', "city": 'Spokane', "state": 'WA'},
            {"name": "Providence St. Luke's Rehabilitation Medical Center", "city": 'Spokane', "state": 'WA'},
            {"name": 'Providence Medford Medical Center', "city": 'Medford', "state": 'OR'},
            {"name": 'Providence St. Joseph Medical Center', "city": 'Polson', "state": 'MT'},
            {"name": 'Providence St. Patrick Hospital', "city": 'Missoula', "state": 'MT'},
            {"name": 'Providence St. Joseph Hospital Eureka', "city": 'Eureka', "state": 'CA'},
            {"name": 'Providence Redwood Memorial Hospital', "city": 'Fortuna', "state": 'CA'},
            {"name": 'Healdsburg Hospital', "city": 'Healdsburg', "state": 'CA'},
            {"name": 'Providence Santa Rosa Memorial Hospital', "city": 'Santa Rosa', "state": 'CA'},
            {"name": 'Providence Queen of the Valley Medical Center', "city": 'Napa', "state": 'CA'},
            {"name": 'Petaluma Valley Hospital', "city": 'Petaluma', "state": 'CA'},
            {"name": 'Providence Holy Cross Medical Center', "city": 'Mission Hills', "state": 'CA'},
            {"name": 'Providence Cedars-Sinai Tarzana Medical Center', "city": 'Tarzana', "state": 'CA'},
            {"name": 'Providence Saint Joseph Medical Center', "city": 'Burbank', "state": 'CA'},
            {"name": 'Providence Little Company of Mary Medical Center Torrance', "city": 'Torrance', "state": 'CA'},
            {"name": 'Providence Little Company of Mary Medical Center San Pedro', "city": 'San Pedro', "state": 'CA'},
            {"name": 'Providence St. Joseph Hospital Orange', "city": 'Orange', "state": 'CA'},
            {"name": 'Providence Mission Hospital Mission Viejo', "city": 'Mission Viejo', "state": 'CA'},
            {"name": 'Providence Mission Hospital Laguna Beach', "city": 'Laguna Beach', "state": 'CA'},
            {"name": 'Providence Valdez Medical Center', "city": 'Valdez', "state": 'AK'},
            {"name": 'Providence Seward Medical Center', "city": 'Seward', "state": 'AK'},
            {"name": 'Covenant Hospital Levelland', "city": 'Levelland', "state": 'TX'},
            {"name": 'Providence Kodiak Island Medical Center', "city": 'Kodiak Island', "state": 'AK'},
            {"name": "Providence Alaska Children's Hospital", "city": 'Anchorage', "state": 'AK'},
            {"name": 'Providence Alaska Medical Center', "city": 'Anchorage', "state": 'AK'},
            {"name": 'Providence St. Elias Specialty Hospital', "city": 'Anchorage', "state": 'AK'},
            {"name": 'Covenant Health Hobbs Hospital', "city": 'Hobbs', "state": 'NM'},
            {"name": 'Grace Surgical Hospital', "city": 'Lubbock', "state": 'TX'},
            {"name": 'Covenant Specialty Hospital', "city": 'Lubbock', "state": 'TX'},
            {"name": "Covenant Children's Hospital", "city": 'Lubbock', "state": 'TX'},
            {"name": 'Covenant Medical Center', "city": 'Lubbock', "state": 'TX'},
        ],
    },
    {
        "company": 'Bon Secours Mercy Health',
        "source_url": 'https://bsmhealth.org/brands/care-delivery/',
        "verified_at": '2026-09-17',
        "hospitals": [
            {"name": 'Bon Secours St. Francis Downtown', "city": 'Greenville', "state": 'SC'},
            {"name": 'Bon Secours St. Francis Eastside', "city": 'Greenville', "state": 'SC'},
            {"name": 'Bon Secours Harbour View Medical Center', "city": 'Suffolk', "state": 'VA'},
            {"name": 'Bon Secours Mary Immaculate Hospital', "city": 'Newport News', "state": 'VA'},
            {"name": 'Bon Secours Maryview Medical Center', "city": 'Portsmouth', "state": 'VA'},
            {"name": 'Bon Secours Southampton Medical Center', "city": 'Franklin', "state": 'VA'},
            {"name": 'Bon Secours Memorial Regional Medical Center', "city": 'Mechanicsville', "state": 'VA'},
            {"name": 'Bon Secours Rappahannock General Hospital', "city": 'Kilmarnock', "state": 'VA'},
            {"name": 'Bon Secours Richmond Community Hospital', "city": 'Richmond', "state": 'VA'},
            {"name": 'Bon Secours Southern Virginia Medical Center', "city": 'Emporia', "state": 'VA'},
            {"name": 'Bon Secours Southside Medical Center', "city": 'Petersburg', "state": 'VA'},
            {"name": 'Bon Secours St. Francis Medical Center', "city": 'Midlothian', "state": 'VA'},
            {"name": "Bon Secours St. Mary's Hospital", "city": 'Richmond', "state": 'VA'},
            {"name": 'Mercy Health - Anderson Hospital', "city": 'Cincinnati', "state": 'OH'},
            {"name": 'Mercy Health - Clermont Hospital', "city": 'Batavia', "state": 'OH'},
            {"name": 'Mercy Health - Fairfield Hospital', "city": 'Fairfield', "state": 'OH'},
            {"name": 'Mercy Health - Kings Mills Hospital', "city": 'Mason', "state": 'OH'},
            {"name": 'Mercy Health - West Hospital', "city": 'Cincinnati', "state": 'OH'},
            {"name": 'The Jewish Hospital - Mercy Health', "city": 'Cincinnati', "state": 'OH'},
            {"name": 'Mercy Health - Marcum and Wallace Hospital', "city": 'Irvine', "state": 'KY'},
            {"name": "Mercy Health - St. Rita's Medical Center", "city": 'Lima', "state": 'OH'},
            {"name": 'Mercy Health - Allen Hospital', "city": 'Oberlin', "state": 'OH'},
            {"name": 'Mercy Health - Lorain Hospital', "city": 'Lorain', "state": 'OH'},
            {"name": 'Mercy Health - Lourdes Hospital', "city": 'Paducah', "state": 'KY'},
            {"name": 'Mercy Health - Urbana Hospital', "city": 'Urbana', "state": 'OH'},
            {"name": 'Mercy Health - Springfield Regional Medical Center', "city": 'Springfield', "state": 'OH'},
            {"name": 'Mercy Health - Defiance Hospital', "city": 'Defiance', "state": 'OH'},
            {"name": 'Mercy Health - Perrysburg Hospital', "city": 'Perrysburg', "state": 'OH'},
            {"name": 'Mercy Health - St. Anne Hospital', "city": 'Toledo', "state": 'OH'},
            {"name": 'Mercy Health - St. Charles Hospital', "city": 'Oregon', "state": 'OH'},
            {"name": 'Mercy Health - St. Vincent Medical Center', "city": 'Toledo', "state": 'OH'},
            {"name": 'Mercy Health - Tiffin Hospital', "city": 'Tiffin', "state": 'OH'},
            {"name": 'Mercy Health - Willard Hospital', "city": 'Willard', "state": 'OH'},
            {"name": 'Mercy Health - St. Elizabeth Boardman Hospital', "city": 'Youngstown', "state": 'OH'},
            {"name": 'Mercy Health - St. Elizabeth Youngstown Hospital', "city": 'Youngstown', "state": 'OH'},
            {"name": 'Mercy Health - St. Joseph Warren Hospital', "city": 'Warren', "state": 'OH'},
            {"name": 'Roper Hospital', "city": 'Charleston', "state": 'SC'},
            {"name": 'Bon Secours St. Francis Hospital', "city": 'Charleston', "state": 'SC'},
            {"name": 'Roper St. Francis Mount Pleasant Hospital', "city": 'Mount Pleasant', "state": 'SC'},
            {"name": 'Roper St. Francis Berkeley Hospital', "city": 'Summerville', "state": 'SC'},
        ],
    },
    {
        "company": 'UPMC',
        "source_url": 'https://www.upmc.com/locations/hospitals',
        "verified_at": '2026-09-17',
        "hospitals": [
            {"name": "UPMC Children's Hospital of Pittsburgh", "city": 'Pittsburgh', "state": 'PA'},
            {"name": 'UPMC East', "city": 'Monroeville', "state": 'PA'},
            {"name": 'UPMC Greene', "city": 'Waynesburg', "state": 'PA'},
            {"name": 'UPMC Horizon - Greenville', "city": 'Greenville', "state": 'PA'},
            {"name": 'UPMC Horizon - Shenango Valley', "city": 'Farrell', "state": 'PA'},
            {"name": 'UPMC Jameson', "city": 'New Castle', "state": 'PA'},
            {"name": 'UPMC Magee-Womens Hospital', "city": 'Pittsburgh', "state": 'PA'},
            {"name": 'UPMC McKeesport', "city": 'McKeesport', "state": 'PA'},
            {"name": 'UPMC Mercy', "city": 'Pittsburgh', "state": 'PA'},
            {"name": 'UPMC Montefiore', "city": 'Pittsburgh', "state": 'PA'},
            {"name": 'UPMC Passavant - Cranberry', "city": 'Cranberry Township', "state": 'PA'},
            {"name": 'UPMC Passavant - McCandless', "city": 'Pittsburgh', "state": 'PA'},
            {"name": 'UPMC Presbyterian', "city": 'Pittsburgh', "state": 'PA'},
            {"name": 'UPMC Shadyside', "city": 'Pittsburgh', "state": 'PA'},
            {"name": 'UPMC St. Margaret', "city": 'Pittsburgh', "state": 'PA'},
            {"name": 'UPMC Washington', "city": 'Washington', "state": 'PA'},
            {"name": 'UPMC Western Psychiatric Hospital', "city": 'Pittsburgh', "state": 'PA'},
            {"name": 'UPMC Chautauqua', "city": 'Jamestown', "state": 'NY'},
            {"name": 'UPMC Hamot', "city": 'Erie', "state": 'PA'},
            {"name": 'UPMC Kane', "city": 'Kane', "state": 'PA'},
            {"name": 'UPMC Northwest', "city": 'Seneca', "state": 'PA'},
            {"name": 'UPMC Carlisle', "city": 'Carlisle', "state": 'PA'},
            {"name": 'UPMC Community Osteopathic', "city": 'Harrisburg', "state": 'PA'},
            {"name": 'UPMC Hanover', "city": 'Hanover', "state": 'PA'},
            {"name": 'UPMC Harrisburg', "city": 'Harrisburg', "state": 'PA'},
            {"name": 'UPMC Lititz', "city": 'Lititz', "state": 'PA'},
            {"name": 'UPMC Memorial', "city": 'York', "state": 'PA'},
            {"name": 'UPMC West Shore', "city": 'Mechanicsburg', "state": 'PA'},
            {"name": 'UPMC Cole', "city": 'Coudersport', "state": 'PA'},
            {"name": 'UPMC Muncy', "city": 'Muncy', "state": 'PA'},
            {"name": 'UPMC Wellsboro', "city": 'Wellsboro', "state": 'PA'},
            {"name": 'UPMC Williamsport', "city": 'Williamsport', "state": 'PA'},
            {"name": 'UPMC Altoona', "city": 'Altoona', "state": 'PA'},
            {"name": 'UPMC Bedford', "city": 'Everett', "state": 'PA'},
            {"name": 'UPMC Somerset', "city": 'Somerset', "state": 'PA'},
            {"name": 'UPMC Western Maryland', "city": 'Cumberland', "state": 'MD'},
        ],
    },
]
